# Generated by Django 3.1.4 on 2020-12-14 16:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('set_number', models.PositiveIntegerField()),
                ('piece_count', models.PositiveSmallIntegerField()),
                ('source', models.CharField(max_length=200)),
                ('release_year', models.PositiveSmallIntegerField()),
                ('minifigures', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('set_series', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=800)),
                ('lego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='legos.lego')),
            ],
        ),
    ]
