# Generated by Django 3.1.4 on 2020-12-14 16:52

from django.db import migrations

def seed(apps, schema_editor):
    Lego = apps.get_model('legos', Lego)

    Lego(name='', set_number= , piece_count= , source='', release_year= , minifigures=['', '', ''], set_series='Star Wars')
    Lego(name='', set_number=, piece_count=, source='', release_year=, minifigures=['', '', ''], set_series='Star Wars')
    Lego(name='', set_number=, piece_count=, source='', release_year=, minifigures=['', '', ''], set_series='Star Wars')
    Lego(name='', set_number=, piece_count=, source='', release_year=, minifigures=['', '', ''], set_series='Star Wars')
    Lego(name='', set_number=, piece_count=, source='', release_year=, minifigures=['', '', ''], set_series='Star Wars')
    Lego(name='', set_number=, piece_count=, source='', release_year=, minifigures=['', '', ''], set_series='Star Wars')
    Lego(name='', set_number=, piece_count=, source='', release_year=, minifigures=['', '', ''], set_series='Star Wars')
    Lego(name='', set_number=, piece_count=, source='', release_year=, minifigures=['', '', ''], set_series='Star Wars')
    Lego(name='', set_number=, piece_count=, source='', release_year=, minifigures=['', '', ''], set_series='Star Wars')
    Lego(name='', set_number=, piece_count=, source='', release_year=, minifigures=['', '', ''], set_series='Star Wars')
    Lego(name='', set_number=, piece_count=, source='', release_year=, minifigures=['', '', ''], set_series='Star Wars')
    Lego(name='', set_number=, piece_count=, source='', release_year=, minifigures=['', '', ''], set_series='Star Wars')
    Lego(name='', set_number=, piece_count=, source='', release_year=, minifigures=['', '', ''], set_series='Star Wars')
    Lego(name='', set_number=, piece_count=, source='', release_year=, minifigures=['', '', ''], set_series='Star Wars')
    Lego(name='', set_number=, piece_count=, source='', release_year=, minifigures=['', '', ''], set_series='Star Wars')
    Lego(name='', set_number=, piece_count=, source='', release_year=, minifigures=['', '', ''], set_series='Star Wars')
    Lego(name='', set_number=, piece_count=, source='', release_year=, minifigures=['', '', ''], set_series='Star Wars')
    Lego(name='', set_number=, piece_count=, source='', release_year=, minifigures=['', '', ''], set_series='Star Wars')
    Lego(name='', set_number=, piece_count=, source='', release_year=, minifigures=['', '', ''], set_series='Star Wars')
    Lego(name='', set_number=, piece_count=, source='', release_year=, minifigures=['', '', ''], set_series='Star Wars')
    

def fallow(apps, schema_editor):
    Lego = apps.get_model('legos', Lego)
    Lego.objects.all().delete()



class Migration(migrations.Migration):

    dependencies = [
        ('legos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
