# Generated by Django 3.1.4 on 2020-12-14 16:52

from django.db import migrations


def seed(apps, schema_editor):
    Lego = apps.get_model('legos', Lego)

    Lego(name='Lightsaber Duel', set_number=7101, piece_count=52, source='Episode I',
         release_year=1999, minifigures=['Qui-Gon Jinn', 'Darth Maul'], set_series='Star Wars').save()
    Lego(name='Droid Fighter', set_number=7111, piece_count=62, source='Episode I',
         release_year=1999, minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Naboo Swamp', set_number=7121, piece_count=82, source='Episode I', release_year=1999,
         minifigures=['Qui-Gon Jinn', 'Jar Jar Binks', 'Battle Droid (2x)'], set_series='Star Wars').save()
    Lego(name='Anakin\'s Podracer', set_number=7131, piece_count=136, source='Episode I', release_year=1999,
         minifigures=['Anakin Skywalker', 'Padme Amidala', 'Pit Droid'], set_series='Star Wars').save()
    Lego(name='Naboo Fighter', set_number=7141, piece_count=179, source='Episode I', release_year=1999,
         minifigures=['Anakin Skywalker', 'R2-D2', 'Battle Droid (2x)'], set_series='Star Wars').save()
    Lego(name='Sith Infiltrator', set_number=7151, piece_count=244, source='Episode I',
         release_year=1999, minifigures=['Darth Maul'], set_series='Star Wars').save()
    Lego(name='Gungan Sub', set_number=7161, piece_count=379, source='Episode I', release_year=1999,
         minifigures=['Obi-Wan kenobi', 'Qui-Gon Jinn', 'Jar Jar Binks'], set_series='Star Wars').save()
    Lego(name='Mos Espa Podrace', set_number=7171, piece_count=896, source='Episode I', release_year=1999, minifigures=[
         'Anakin Skywalker', 'Gasgano', 'Jar Jar Binks', 'Padme Amidala', 'Pit Droid (3x)', 'Qui-Gon Jinn', 'R2-D2', 'Sebulba'], set_series='Star Wars').save()
    Lego(name='TIE Fighter and Y-Wing', set_number=7150, piece_count=409, source='Episode IV',
         release_year=1999, minifigures=['Darth Vader', 'R5-D4', 'Dutch Vander'], set_series='Star Wars').save()
    Lego(name='Landspeeder', set_number=7110, piece_count=49, source='Episode IV',
         release_year=1999, minifigures=['Luke Skywalker', 'Ben Kenobi'], set_series='Star Wars').save()
    Lego(name='X-Wing Fighter', set_number=7140, piece_count=266, source='Episode IV', release_year=1999,
         minifigures=['Luke Skywalker', 'Biggs Darklighter', 'R2-D2', 'Rebel Technician'], set_series='Star Wars').save()
    Lego(name='Snowspeeder', set_number=7130, piece_count=215, source='Episode V', release_year=1999,
         minifigures=['Luke Skywalker', 'Dak Ralter', 'Hoth Rebel'], set_series='Star Wars').save()
    Lego(name='Speeder Bikes', set_number=7128, piece_count=93, source='Episode VI', release_year=1999,
         minifigures=['Luke Skywalker', 'Scout Trooper (2x)'], set_series='Star Wars').save()
    Lego(name='Gungan Patrol', set_number=7115, piece_count=77, source='Episode I', release_year=2000, minifigures=['Jar Jar Binks', 'Gungan Soldier'], set_series='Star Wars').save()
    Lego(name='Flash Speeder', set_number=7124, piece_count=106, source='Episode I', release_year=2000, minifigures=['Naboo Security Officer'], set_series='Star Wars').save()
    Lego(name='Trade Federation AAT', set_number=7155, piece_count=158, source='Episode I', release_year=2000, minifigures=['Battle Droid (2x)'], set_series='Star Wars').save()
    Lego(name='Star Wars Bucket', set_number=7159, piece_count=292, source='Episode I', release_year=2000, minifigures=['Aldar Beedo', 'Anakin Skywalker', 'Jar Jar Binks'], set_series='Star Wars').save()
    Lego(name='Trade Federation MTT', set_number=7184, piece_count=470, source='Episode I', release_year=2000, minifigures=['Batlle Droid (7x)'], set_series='Star Wars').save()
    Lego(name='Technic Pit Droid', set_number=8000, piece_count=223, source='Episode I', release_year=2000, minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Technic Battle Droid', set_number=8001, piece_count=363, source='Episode I', release_year=2000, minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Technic Destroyer Droid', set_number=8002, piece_count=558, source='Episode I', release_year=2000, minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Millennium Falcon', set_number=7190, piece_count=663, source='Episode IV', release_year=2000, minifigures=['Han Solo', 'C-3PO', 'Chewbacca', 'Luke Skywalker', 'Princess Leia', 'R2-D2'], set_series='Star Wars').save()
    Lego(name='UCS X-Wing Fighter', set_number=7191, piece_count=1300, source='Episode IV', release_year=2000, minifigures=['R2-D2'], set_series='Star Wars').save()
    Lego(name='Slave I', set_number=7144, piece_count=166, source='Episode V', release_year=2000, minifigures=['Boba Fett', 'Han Solo in Carbonite'], set_series='Star Wars').save()
    Lego(name='A-Wing', set_number=7134, piece_count=125, source='Episode VI', release_year=2000, minifigures=['Rebel Engineer', 'Rebel A-Wing Pilot'], set_series='Star Wars').save()
    Lego(name='Desert Skiff', set_number=7104, piece_count=55, source='Episode VI', release_year=2000, minifigures=['Han Solo', 'Luke Skywalker'], set_series='Star Wars').save()
    Lego(name='UCS TIE Interceptor', set_number=7181, piece_count=703, source='Episode VI', release_year=2000, minifigures=['None'], set_series='Star Wars').save()
    Lego(name='B-Wing at Rebel Control Center', set_number=7180, piece_count=338, source='Episode VI', release_year=2000, minifigures=['R5-D4', 'Rebel B-Wing Pilot', 'Rebel Technician'], set_series='Star Wars').save()


def fallow(apps, schema_editor):
    Lego = apps.get_model('legos', Lego)
    Lego.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('legos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
