# Generated by Django 3.1.4 on 2020-12-17 17:50

from django.db import migrations


def fallow(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')
    Lego.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('legos', '0002_auto_20201214_1901'),
    ]

    operations = [
        migrations.RunPython(fallow)
    ]
