# Generated by Django 3.1.4 on 2021-01-06 18:03

from django.db import migrations


def seed(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')

    Lego(name='Mini AT-TE', set_number=4495, piece_count=63, source='Episode II', release_year=2004,
         image_url='https://images.brickset.com/sets/images/4495-1.jpg?200310020127', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Mos Eisley Cantina', set_number=4501, piece_count=193, source='Episode IV', release_year=2004,
         image_url='https://images.brickset.com/sets/images/4501-1.jpg?200709280614', minifigures=['Greedo', 'Han Solo', 'Luke Skywalker', 'Ben Kenobi', 'Sand-Trooper'], set_series='Star Wars').save()
    Lego(name='TIE Fighter and Y-Wing', set_number=7262, piece_count=412, source='Episode IV', release_year=2004,
         image_url='https://images.brickset.com/sets/images/7262-1.jpg?200709280622', minifigures=['Darth Vader', 'R5-D4', 'Y-Wing Rebel Pilot'], set_series='Star Wars').save()
    Lego(name='TIE Fighter Collection', set_number=10131, piece_count=682, source='Episode IV', release_year=2004,
         image_url='https://images.brickset.com/sets/images/10131-1.jpg?200801171242', minifigures=['Darth Vader', 'Droid Brain', 'TIE Fighter Pilot (2x)'], set_series='Star Wars').save()
    Lego(name='Y-Wing Attack Starfighter', set_number=10134, piece_count=1473, source='Episode IV', release_year=2004,
         image_url='https://images.brickset.com/sets/images/10134-1.jpg?200409260519', minifigures=['R5-D4'], set_series='Star Wars').save()
    Lego(name='Mini Star Destroyer', set_number=4492, piece_count=87, source='Episode IV', release_year=2004,
         image_url='https://images.brickset.com/sets/images/4492-1.jpg?200310020124', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Mini X-Wing Fighter', set_number=6963, piece_count=41, source='Episode IV', release_year=2004,
         image_url='https://images.brickset.com/sets/images/6963-1.jpg?200405251034', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Mini Boba fett\'s Slave I', set_number=6964, piece_count=25, source='Episode V', release_year=2004,
         image_url='https://images.brickset.com/sets/images/6964-1.jpg?200405251035', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Rebel Snowspeeder', set_number=4500, piece_count=214, source='Episode V', release_year=2004,
         image_url='https://images.brickset.com/sets/images/4500-1.jpg?200709280613', minifigures=['Luke Skywalker', 'Dak Ralter', 'Hoth Rebel'], set_series='Star Wars').save()
    Lego(name='X-Wing Fighter', set_number=4502, piece_count=563, source='Episode V', release_year=2004,
         image_url='https://images.brickset.com/sets/images/4502-1.jpg?200709280614', minifigures=['Luke Skywalker', 'Yoda', 'R2-D2'], set_series='Star Wars').save()
    Lego(name='Rebel Snowspeeder', set_number=10129, piece_count=1457, source='Episode V', release_year=2004,
         image_url='https://images.brickset.com/sets/images/10129-1.jpg?200706300826', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Millennium Falcon', set_number=4504, piece_count=985, source='Episode V', release_year=2004,
         image_url='https://images.brickset.com/sets/images/4504-1.jpg?200709280614', minifigures=['Han Solo', 'C-3PO', 'Chewbacca', 'Princess Leia', 'Snowtrooper'], set_series='Star Wars').save()
    Lego(name='Mini TIE Interceptor', set_number=6965, piece_count=32, source='Episode VI', release_year=2004,
         image_url='https://images.brickset.com/sets/images/6965-1.jpg?200405251036', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Mini Imperial Shuttle', set_number=4494, piece_count=82, source='Episode VI', release_year=2004,
         image_url='https://images.brickset.com/sets/images/4494-1.jpg?200310020126', minifigures=['None'], set_series='Star Wars').save()

    Lego(name='Mini Jedi Starfighter', set_number=6966, piece_count=38, source='Episode III', release_year=2005,
         image_url='https://images.brickset.com/sets/images/6966-1.jpg?200503250152', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Mini ARC Fighter', set_number=6967, piece_count=42, source='Episode III', release_year=2005,
         image_url='https://images.brickset.com/sets/images/6967-1.jpg?200505180352', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Clone Scout Walker', set_number=7250, piece_count=108, source='Episode III', release_year=2005,
         image_url='https://images.brickset.com/sets/images/7250-1.jpg?200709280637', minifigures=['Clone Trooper'], set_series='Star Wars').save()
    Lego(name='Darth Vader Transformation', set_number=7251, piece_count=53, source='Episode III', release_year=2005,
         image_url='https://images.brickset.com/sets/images/7251-1.jpg?200709280637', minifigures=['Darth Vader', 'Anakin Skywalker', 'Medical Droid'], set_series='Star Wars').save()
    Lego(name='Droid Tri-Fighter', set_number=7252, piece_count=148, source='Episode III', release_year=2005,
         image_url='https://images.brickset.com/sets/images/7252-1.jpg?200709280637', minifigures=['Buzz Droid'], set_series='Star Wars').save()
    Lego(name='General Grievous Chase', set_number=7255, piece_count=111, source='Episode III', release_year=2005,
         image_url='https://images.brickset.com/sets/images/7255-1.jpg?200709280637', minifigures=['Obi-Wan Kenobi', 'General Grievous'], set_series='Star Wars').save()
    Lego(name='Jedi Starfighter and Vulture Droid', set_number=7256, piece_count=202, source='Episode III', release_year=2005,
         image_url='https://images.brickset.com/sets/images/7256-1.jpg?200709280637', minifigures=['Anakin Skywalker'], set_series='Star Wars').save()
    Lego(name='Ultimate Lightsaber Duel', set_number=7257, piece_count=282, source='Episode III', release_year=2005,
         image_url='https://images.brickset.com/sets/images/7257-1.jpg?200709280637', minifigures=['Anakin Skywalker', 'Obi-Wan Kenobi'], set_series='Star Wars').save()
    Lego(name='Wookiee Attack', set_number=7258, piece_count=366, source='Episode III', release_year=2005,
         image_url='https://images.brickset.com/sets/images/7258-1.jpg?200709280638', minifigures=['Battle Droid (2x)', 'Dwarf Spider Droid', 'Wookiee Warrior (2x)'], set_series='Star Wars').save()
    Lego(name='ARC-170 Starfighter', set_number=7259, piece_count=396, source='Episode III', release_year=2005,
         image_url='https://images.brickset.com/sets/images/7259-1.jpg?200709280638', minifigures=['Clone Pilot (3x)', 'R5-D4'], set_series='Star Wars').save()
    Lego(name='Wookiee Catamaran', set_number=7260, piece_count=376, source='Episode III', release_year=2005,
         image_url='https://images.brickset.com/sets/images/7260-1.jpg?200709280638', minifigures=['Chewbacca', 'Clone Trooper (2x, green markings)', 'Luminara Unduli', 'Wookiee Warrior', 'Yoda'], set_series='Star Wars').save()
    Lego(name='Clone Turbo Tank', set_number=7261, piece_count=801, source='Episode III', release_year=2005,
         image_url='https://images.brickset.com/sets/images/7261-1.jpg?200709280638', minifigures=['Battle Droid (2x)', 'Clone Trooper', 'Aerial Trooper', 'Clone Trooper (yellow markings)', 'Mace Windu', 'Kashyyyk Trooper'], set_series='Star Wars').save()
    Lego(name='Ultimate Space Battle', set_number=7283, piece_count=567, source='Episode III', release_year=2005,
         image_url='https://images.brickset.com/sets/images/7283-1.jpg?201910160842', minifigures=['Anakin Skywalker', 'Obi-Wan Kenobi', 'Buzz Droid (2x)'], set_series='Star Wars').save()
    Lego(name='Episode III Collector\'s Set', set_number=65771, piece_count=544, source='Episode III', release_year=2005,
         image_url='https://images.brickset.com/sets/images/65771-1.jpg?201009240929', minifigures=['Clone Pilot (3x)', 'Buzz Droid'], set_series='Star Wars').save()
    Lego(name='TIE Fighter', set_number=7263, piece_count=159, source='Episode IV', release_year=2005,
         image_url='https://images.brickset.com/sets/images/7263-1.jpg?200709280623', minifigures=['Darth Vader', 'TIE Fighter Pilot'], set_series='Star Wars').save()
    Lego(name='Sandcrawler', set_number=10144, piece_count=1669, source='Episode IV', release_year=2005,
         image_url='https://images.brickset.com/sets/images/10144-1.jpg?200709280627', minifigures=['ASP Droid', 'C-3PO', 'Gonk Droid', 'Jawa (3x)', 'Owen Lars', 'R1-G4', 'R2-D2', 'R5-D4', 'Treadwell Droid'], set_series='Star Wars').save()
    Lego(name='Imperial Inspection', set_number=7264, piece_count=367, source='Episode VI', release_year=2005,
         image_url='https://images.brickset.com/sets/images/7264-1.jpg?200709280623', minifigures=['Darth Vader', 'Emperor Palpatine', 'Imperial Officer (2x)', 'Royal Guard (2x)', 'Stormtrooper (4x)'], set_series='Star Wars').save()
    Lego(name='Death Star II', set_number=10143, piece_count=3441, source='Episode VI', release_year=2005,
         image_url='https://images.brickset.com/sets/images/10143-1.jpg?200709280626', minifigures=['None'], set_series='Star Wars').save()

    Lego(name='V-Wing Fighter', set_number=6205, piece_count=118, source='Episode III', release_year=2006,
         image_url='https://images.brickset.com/sets/images/6205-1.jpg?200709280637', minifigures=['Clone Pilot'], set_series='Star Wars').save()
    Lego(name='Imperial Star Destroyer', set_number=6211, piece_count=1367, source='Episode IV', release_year=2006,
         image_url='https://images.brickset.com/sets/images/6211-1.jpg?200709280616', minifigures=['Darth Vader', 'Grand Moff Tarkin', 'Imperial Officer', 'Mouse Droid', 'R2-D5', 'Royal Guard (2x)', 'Stormtrooper (2x)'], set_series='Star Wars').save()
    Lego(name='Vader\'s TIE Advanced', set_number=10175, piece_count=1212, source='Episode IV', release_year=2006,
         image_url='https://images.brickset.com/sets/images/10175-1.jpg?200608260646', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='X-Wing Fighter', set_number=6212, piece_count=437, source='Episode IV', release_year=2006,
         image_url='https://images.brickset.com/sets/images/6212-1.jpg?200709280616', minifigures=['Chewbacca', 'Han Solo', 'Luke Skywalker', 'Princess Leia', 'R2-D2', 'Wedge Antilles'], set_series='Star Wars').save()
    Lego(name='Slave I', set_number=6209, piece_count=537, source='Episode V', release_year=2006,
         image_url='https://images.brickset.com/sets/images/6209-1.jpg?200709280615', minifigures=['Boba Fett', 'Bespin Guard', 'Dengar', 'Han Solo in Carbonite', 'IG-88'], set_series='Star Wars').save()
    Lego(name='TIE Interceptor', set_number=6206, piece_count=212, source='Episode VI', release_year=2006,
         image_url='https://images.brickset.com/sets/images/6206-1.jpg?200709280614', minifigures=['TIE Fighter Pilot'], set_series='Star Wars').save()
    Lego(name='A-Wing Fighter', set_number=6207, piece_count=194, source='Episode VI', release_year=2006,
         image_url='https://images.brickset.com/sets/images/6207-1.jpg?200709280615', minifigures=['Rebel A-Wing Pilot', 'Rebel Techinician'], set_series='Star Wars').save()
    Lego(name='B-Wing Fighter', set_number=6208, piece_count=435, source='Episode VI', release_year=2006,
         image_url='https://images.brickset.com/sets/images/6208-1.jpg?200709280615', minifigures=['Rebel B-Wing Pilot', 'Ten Numb'], set_series='Star Wars').save()
    Lego(name='Jabba\'s Sail Barge', set_number=6210, piece_count=781, source='Episode VI', release_year=2006,
         image_url='https://images.brickset.com/sets/images/6210-1.jpg?200709280616', minifigures=['Boba Fett', 'Gamorrean Guard', 'Han Solo', 'Jabba the Hutt', 'Lando Calrissian', 'Luke Skywalker', 'Princess Leia', 'R2-D2'], set_series='Star Wars').save()
    Lego(name='UCS Imperial AT-ST', set_number=10174, piece_count=1068, source='Episode VI', release_year=2006,
         image_url='https://images.brickset.com/sets/images/10174-1.jpg?200706300825', minifigures=['None'], set_series='Star Wars').save()

    Lego(name='Naboo N-1 Starfighter and Vulture Droid', set_number=7660, piece_count=280, source='Episode I', release_year=2007,
         image_url='https://images.brickset.com/sets/images/7660-1.jpg?200709280633', minifigures=['Anakin Skywalker', 'R2-D2', 'Naboo Fighter Pilot'], set_series='Star Wars').save()
    Lego(name='Trade Federation MTT', set_number=7662, piece_count=1330, source='Episode I', release_year=2007,
         image_url='https://images.brickset.com/sets/images/7662-1.jpg?200709280633', minifigures=['Battle Droid (16x)', 'Battle Droid Pilot (2x)', 'Battle Droid Security (2x)', 'Droideka'], set_series='Star Wars').save()
    Lego(name='Sith Infiltrator', set_number=7663, piece_count=310, source='Episode I', release_year=2007,
         image_url='https://images.brickset.com/sets/images/7663-1.jpg?200710080822', minifigures=['Darth Maul'], set_series='Star Wars').save()
    Lego(name='Republic Cruiser', set_number=7665, piece_count=919, source='Episode I', release_year=2007,
         image_url='https://images.brickset.com/sets/images/7665-1.jpg?200709280634', minifigures=['Obi-Wan Kenobi', 'Qui-Gon Jinn', 'R2-R7', 'Republic Captain', 'Republic Pilot'], set_series='Star Wars').save()
    Lego(name='General Grievous Starfighter', set_number=7656, piece_count=232, source='Episode III', release_year=2007,
         image_url='https://images.brickset.com/sets/images/7656-1.jpg?200709280639', minifigures=['General Grievous'], set_series='Star Wars').save()
    Lego(name='Jedi Starfighter with Hyperdrive Booster Ring', set_number=7661, piece_count=575, source='Episode III', release_year=2007,
         image_url='https://images.brickset.com/sets/images/7661-1.jpg?200709280639', minifigures=['Obi-Wan Kenobi', 'Kit Fisto'], set_series='Star Wars').save()
    Lego(name='Droids Battle Pack', set_number=7654, piece_count=102, source='Episode III', release_year=2007,
         image_url='https://images.brickset.com/sets/images/7654-1.jpg?200709280638', minifigures=['Battle Droid (4x)', 'Super Battle Droid (3x)'], set_series='Star Wars').save()
    Lego(name='Clone Troopers Battle Pack', set_number=7655, piece_count=58, source='Episode III', release_year=2007,
         image_url='https://images.brickset.com/sets/images/7655-1.jpg?200709280639', minifigures=['Clone Trooper (2x)', 'Clone Shock Trooper', ' Clone Star Corps Trooper'], set_series='Star Wars').save()
    Lego(name='Y-Wing Fighter', set_number=7658, piece_count=454, source='Episode IV', release_year=2007,
         image_url='https://images.brickset.com/sets/images/7658-1.jpg?200709280623', minifigures=['R5-D4', 'Rebel Y-Wing Pilot'], set_series='Star Wars').save()
    Lego(name='Imperial Landing Craft', set_number=7659, piece_count=471, source='Episode IV', release_year=2007,
         image_url='https://images.brickset.com/sets/images/7659-1.jpg?200709280624', minifigures=['Sandtrooper (2x)', 'Stormtrooper (2x)', 'TIE Interceptor Pilot'], set_series='Star Wars').save()
    Lego(name='UCS Millennium Falcon', set_number=10179, piece_count=5197, source='Episode IV', release_year=2007,
         image_url='https://images.brickset.com/sets/images/10179-1.jpg?200709280259', minifigures=['Luke Skywalker', 'Han Solo', 'Princess Leia', 'Chewbacca', 'Obi-Wan Kenobi'], set_series='Star Wars').save()
    Lego(name='Hoth Rebel Base', set_number=7666, piece_count=548, source='Episode V', release_year=2007,
         image_url='https://images.brickset.com/sets/images/7666-1.jpg?200709280624', minifigures=['Dak Ralter', 'Hoth Rebel (2x)', 'Imperial Probe Droid', 'K-3PO', 'Luke Skywalker', 'Snowtrooper (2x)'], set_series='Star Wars').save()
    Lego(name='Motorized Walking AT-AT', set_number=10178, piece_count=1137, source='Episode V', release_year=2007,
         image_url='https://images.brickset.com/sets/images/10178-1.jpg?200712051219', minifigures=['Luke Skywalker', 'AT-AT Driver', 'General Veers', 'Snowtrooper'], set_series='Star Wars').save()
    Lego(name='AT-ST', set_number=7657, piece_count=244, source='Episode VI', release_year=2007,
         image_url='https://images.brickset.com/sets/images/7657-1.jpg?200709280623', minifigures=['Imperial AT-ST Pilot'], set_series='Star Wars').save()
    Lego(name='TIE Crawler', set_number=7664, piece_count=548, source='Expanded Universe', release_year=2007,
         image_url='https://images.brickset.com/sets/images/7664-1.jpg?200801171242', minifigures=['Shadow Trooper (2x)'], set_series='Star Wars').save()


def fallow(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')
    Lego.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('legos', '0005_auto_20210106_1755'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
