# Generated by Django 3.1.4 on 2021-01-08 18:52

from django.db import migrations

def seed(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')

    Lego(name='Hailfire Droid & Spider Droid', set_number=7670, piece_count=249, source='Episode II', release_year=2008,
         image_url='https://images.brickset.com/sets/images/7670-1.jpg?200712160632', minifigures=['Battle Droid Commander', 'Battle Droid (2x)', 'Dwarf Spider Droid', 'Super Battle Droid'], set_series='Star Wars').save()
    Lego(name='AT-AP Walker', set_number=7671, piece_count=392, source='Episode III', release_year=2008,
         image_url='https://images.brickset.com/sets/images/7671-1.jpg?200712160629', minifigures=['Clone Shock Trooper (2x)'], set_series='Star Wars').save()
    Lego(name='General Grievous', set_number=10186, piece_count=1085, source='Episode III', release_year=2008,
         image_url='https://images.brickset.com/sets/images/10186-1.jpg?200804080442', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Mini Clone Turbo Tank', set_number=20006, piece_count=64, source='Episode III', release_year=2008,
         image_url='https://images.brickset.com/sets/images/20006-1.jpg?201704051017', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Death Star', set_number=10188, piece_count=3803, source='Episode IV', release_year=2008,
         image_url='https://images.brickset.com/sets/images/10188-1.jpg?200807260532', minifigures=['Assassin Droid', 'C-3PO', 'Chewbacca', 'Emperor Palpatine', 'Darth Vader', 'Grand Moff Tarkin', 'Han Solo', 'Han Solo (Stormtrooper Outfit)', 'Imperial Trooper', 'Interrogation Droid', 'Luke Skywalker (Jedi Knight)', 'Luke Skywalker (Stormtrooper Outfit)', 'Luke Skywalker', 'Mouse Droid', 'Obi-Wan Kenobi', 'Princess Leia', 'Protocol Droid', 'R2-D2', 'R2-Q5', 'Royal Guard (2x)', 'Stormtrooper (2x)'], set_series='Star Wars').save()
    Lego(name='Mini TIE Fighter', set_number=8028, piece_count=44, source='Episode IV', release_year=2008,
         image_url='https://images.brickset.com/sets/images/8028-1.jpg?200808030513', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Mini Rebel Snowspeeder', set_number=8029, piece_count=66, source='Episode V', release_year=2008,
         image_url='https://images.brickset.com/sets/images/8029-1.jpg?200811030333', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Rebel Scout Speeder', set_number=7668, piece_count=82, source='Expanded Universe', release_year=2008,
         image_url='https://images.brickset.com/sets/images/7668-1.jpg?200712160629', minifigures=['Rebel Fleet Trooper (4x)'], set_series='Star Wars').save()
    Lego(name='Imperial Dropship', set_number=7667, piece_count=81, source='Expanded Universe', release_year=2008,
         image_url='https://images.brickset.com/sets/images/7667-1.jpg?200801171243', minifigures=['Stormtrooper (3x)', 'Shadow Trooper'], set_series='Star Wars').save()
    Lego(name='Rogue Shadow', set_number=7672, piece_count=482, source='Expanded Universe', release_year=2008,
         image_url='https://images.brickset.com/sets/images/7672-1.jpg?200712210130', minifigures=['Darth Vader', 'Darth Vader\'s Apprentice', 'Juno Eclipse'], set_series='Star Wars').save()
    Lego(name='Anakin\'s Jedi Starfighter', set_number=7669, piece_count=153, source='Clone Wars', release_year=2008,
         image_url='https://images.brickset.com/sets/images/7669-1.jpg?200712210129', minifigures=['Anakin Skywalker', 'R2-D2'], set_series='Star Wars').save()
    Lego(name='Magna Guard Starfighter', set_number=7673, piece_count=431, source='Clone Wars', release_year=2008,
         image_url='https://images.brickset.com/sets/images/7673-1.jpg?200807160536', minifigures=['Magna Guard (2x)'], set_series='Star Wars').save()
    Lego(name='V-19 Torrent', set_number=7674, piece_count=471, source='Clone Wars', release_year=2008,
         image_url='https://images.brickset.com/sets/images/7674-1.jpg?200807170546', minifigures=['Clone Pilot'], set_series='Star Wars').save()
    Lego(name='AT-TE Walker', set_number=7675, piece_count=798, source='Clone Wars', release_year=2008,
         image_url='https://images.brickset.com/sets/images/7675-1.jpg?200807200942', minifigures=['Ahsoka Tano', 'Anakin Skywalker', 'Battle Droid', 'Captain Rex', 'Clone Trooper', 'Rotta the Huttlet'], set_series='Star Wars').save()
    Lego(name='Republic Attack Gunship', set_number=7676, piece_count=1034, source='Clone Wars', release_year=2008,
         image_url='https://images.brickset.com/sets/images/7676-1.jpg?200807230101', minifigures=['Asajj Ventress', 'Clone Trooper', 'Commander Cody', 'Probe Droid', 'Obi-Wan Kenobi', 'Plo Koon'], set_series='Star Wars').save()
    Lego(name='Droid Gunship', set_number=7678, piece_count=329, source='Clone Wars', release_year=2008,
         image_url='https://images.brickset.com/sets/images/7678-1.jpg?200807170546', minifigures=['Battle Droid (3x)'], set_series='Star Wars').save()
    Lego(name='Republic Fighter Tank', set_number=7679, piece_count=592, source='Clone Wars', release_year=2008,
         image_url='https://images.brickset.com/sets/images/7679-1.jpg?200807261246', minifigures=['Clone Trooper', 'Clone Trooper (With Armor)'], set_series='Star Wars').save()
    Lego(name='The Twilight', set_number=7680, piece_count=882, source='Clone Wars', release_year=2008,
         image_url='https://images.brickset.com/sets/images/7680-1.jpg?200807261242', minifigures=['Anakin Skywalker', 'Ahsoka Tano', 'R2-D2', 'Rotta the Huttlet'], set_series='Star Wars').save()
    Lego(name='Separatist Spider Droid', set_number=7681, piece_count=206, source='Clone Wars', release_year=2008,
         image_url='https://images.brickset.com/sets/images/7681-1.jpg?200807261240', minifigures=['Battle Droid Commander', 'Battle Droid', 'Clone Trooper', 'Commander Fox', 'Super Battle Droid'], set_series='Star Wars').save()
    Lego(name='Mini V-19 Torrent', set_number=8031, piece_count=66, source='Clone Wars', release_year=2008,
         image_url='https://images.brickset.com/sets/images/8031-1.jpg?200809130416', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Mini Republic Attack Cruiser', set_number=20007, piece_count=84, source='Clone Wars', release_year=2008,
         image_url='https://images.brickset.com/sets/images/20007-1.jpg?200903050507', minifigures=['None'], set_series='Star Wars').save()

    Lego(name='Midi-Scale Millennium Falcon', set_number=7778, piece_count=356, source='Episode IV', release_year=2009,
         image_url='https://images.brickset.com/sets/images/7778-1.jpg?200904250333', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Tantive IV', set_number=10198, piece_count=1408, source='Episode IV', release_year=2009,
         image_url='https://images.brickset.com/sets/images/10198-1.jpg?200905080733', minifigures=['R2-D2', 'C-3PO', 'Princess Leia', 'Captain Antilles', 'Rebel Fleet Trooper'], set_series='Star Wars').save()
    Lego(name='Darth Vader\'s TIE Fighter', set_number=8017, piece_count=251, source='Episode IV', release_year=2009,
         image_url='https://images.brickset.com/sets/images/8017-1.jpg?200812011049', minifigures=['Darth Vader'], set_series='Star Wars').save()
    Lego(name='Echo Base', set_number=7749, piece_count=155, source='Episode V', release_year=2009,
         image_url='https://images.brickset.com/sets/images/7749-1.jpg?200905210339', minifigures=['Han Solo (Parka)', 'Hoth Rebel (2x)', 'Snowtrooper (2x)'], set_series='Star Wars').save()
    Lego(name='Home One Mon Calamari Star Cruiser', set_number=7754, piece_count=789, source='Episode VI', release_year=2009,
         image_url='https://images.brickset.com/sets/images/7754-1.jpg?200812230554', minifigures=['Admiral Ackbar', 'Crix Madine', 'Lando Calrissian (General)', 'Mon Calamari Officer', 'Mon Mothma', 'Rebel A-Wing Pilot'], set_series='Star Wars').save()
    Lego(name='The Battle of Endor', set_number=8038, piece_count=890, source='Episode VI', release_year=2009,
         image_url='https://images.brickset.com/sets/images/8038-1.jpg?200905200857', minifigures=['Chewbacca', 'Han Solo', 'Chief Chirpa (Ewok)', 'Paploo (Ewok)', 'Endor Rebel Commando (2x)', 'Imperial Trooper', 'Scout Trooper', 'Princess Leia (Endor)', 'R2-D2'], set_series='Star Wars').save()
    Lego(name='Mini Imperial Speeder Bike', set_number=30005, piece_count=33, source='Episode VI', release_year=2009,
         image_url='https://images.brickset.com/sets/images/30005-1.jpg?200909010510', minifigures=['Stormtrooper'], set_series='Star Wars').save()
    Lego(name='Mini Battle Droid on STAP', set_number=30004, piece_count=28, source='Clone Wars', release_year=2009,
         image_url='https://images.brickset.com/sets/images/30004-1.jpg?200909020356', minifigures=['Battle Droid'], set_series='Star Wars').save()
    Lego(name='Mini Clone Walker', set_number=30006, piece_count=31, source='Clone Wars', release_year=2009,
         image_url='https://images.brickset.com/sets/images/30006-1.jpg?200909010513', minifigures=['Clone Trooper'], set_series='Star Wars').save()
    Lego(name='Mini AT-TE', set_number=20009, piece_count=94, source='Clone Wars', release_year=2009,
         image_url='https://images.brickset.com/sets/images/20009-1.jpg?200907070410', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Mini Republic Gunship', set_number=20010, piece_count=94, source='Clone Wars', release_year=2009,
         image_url='https://images.brickset.com/sets/images/20010-1.jpg?200911100252', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Corporate Alliance Tank Droid', set_number=7748, piece_count=216, source='Clone Wars', release_year=2009,
         image_url='https://images.brickset.com/sets/images/7748-1.jpg?200905051225', minifigures=['Clone Jet Trooper (2x)', 'Battle Droid (2x)'], set_series='Star Wars').save()
    Lego(name='Ahsoka\'s Starfighter and Vulture Droids', set_number=7751, piece_count=291, source='Clone Wars', release_year=2009,
         image_url='https://images.brickset.com/sets/images/7751-1.jpg?200812240920', minifigures=['Ahsoka Tano', 'Buzz Droid (2x)', 'R7-A7'], set_series='Star Wars').save()
    Lego(name='Count Dooku\'s Solar Sailer', set_number=7752, piece_count=385, source='Clone Wars', release_year=2009,
         image_url='https://images.brickset.com/sets/images/7752-1.jpg?200812240920', minifigures=['Count Dooku', 'Magna Guard (2x)', 'Pilot Droid'], set_series='Star Wars').save()
    Lego(name='Pirate Tank', set_number=7753, piece_count=372, source='Clone Wars', release_year=2009,
         image_url='https://images.brickset.com/sets/images/7753-1.jpg?200904250325', minifigures=['Hondo Ohnaka', 'Obi-Wan Kenobi', 'Turk Falso'], set_series='Star Wars').save()
    Lego(name='Clone Walker Battle Pack', set_number=8014, piece_count=72, source='Clone Wars', release_year=2009,
         image_url='https://images.brickset.com/sets/images/8014-1.jpg?200812111117', minifigures=['Clone Commander', 'Clone Gunner', 'Clone Trooper (2x)'], set_series='Star Wars').save()
    Lego(name='Assassin Droids Battle Pack', set_number=8015, piece_count=94, source='Clone Wars', release_year=2009,
         image_url='https://images.brickset.com/sets/images/8015-1.jpg?200812111117', minifigures=['Assassin Droid (3x)', 'Assassin Droid Elite (2x)'], set_series='Star Wars').save()
    Lego(name='Hyena Droid Bomber', set_number=8016, piece_count=232, source='Clone Wars', release_year=2009,
         image_url='https://images.brickset.com/sets/images/8016-1.jpg?200812111117', minifigures=['Rocket Battle Droid (3x)'], set_series='Star Wars').save()
    Lego(name='AAT', set_number=8018, piece_count=407, source='Clone Wars', release_year=2009,
         image_url='https://images.brickset.com/sets/images/8018-1.jpg?200812111117', minifigures=['Battle Droid (2x)', 'Clone Trooper', 'Super Battle Droid (3x)', 'Yoda'], set_series='Star Wars').save()
    Lego(name='Republic Attack Shuttle', set_number=8019, piece_count=636, source='Clone Wars', release_year=2009,
         image_url='https://images.brickset.com/sets/images/8019-1.jpg?200812111117', minifigures=['Clone Pilot', 'Clone Trooper', 'Mace Windu'], set_series='Star Wars').save()
    Lego(name='Separatist Shuttle', set_number=8036, piece_count=259, source='Clone Wars', release_year=2009,
         image_url='https://images.brickset.com/sets/images/8036-1.jpg?200905210339', minifigures=['Battle Droid Pilot', 'Battle Droid (2x)', 'Nute Gunray', 'Onaconda Farr'], set_series='Star Wars').save()
    Lego(name='Anakin\'s Y-Wing Starfighter', set_number=8037, piece_count=570, source='Clone Wars', release_year=2009,
         image_url='https://images.brickset.com/sets/images/8037-1.jpg?200905210339', minifigures=['Anakin Skywalker', 'Ahsoka Tano', 'R2-D2'], set_series='Star Wars').save()
    Lego(name='Mini General Grievous Starfighter', set_number=8033, piece_count=44, source='Clone Wars', release_year=2009,
         image_url='https://images.brickset.com/sets/images/8033-1.jpg?200901170359', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Venator-Class Republic Attack Cruiser', set_number=8039, piece_count=1170, source='Clone Wars', release_year=2009,
         image_url='https://images.brickset.com/sets/images/8039-1.jpg?200901100449', minifigures=['Chancellor Palpatine', 'Senate Commando (2x)', 'Clone Gunner', 'Clone Pilot'], set_series='Star Wars').save()
    Lego(name='Republic Dropship with AT-OT', set_number=10195, piece_count=1758, source='Clone Wars', release_year=2009,
         image_url='https://images.brickset.com/sets/images/10195-1.jpg?200903231116', minifigures=['Clone Trooper (6x)', 'Clone Pilot (2x)'], set_series='Star Wars').save()

    # Lego(name='', set_number=, piece_count=, source='', release_year=,
    #      image_url='', minifigures=['', '', ''], set_series='Star Wars').save()


def fallow(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')
    Lego.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('legos', '0006_auto_20210106_1803'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
