# Generated by Django 3.1.4 on 2021-01-11 21:33

from django.db import migrations


def seed(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')

    Lego(name='Obi-Wan\'s Jedi Starfighter', set_number=10215, piece_count=676, source='Episode II', release_year=2010,
         image_url='https://images.brickset.com/sets/images/10215-1.jpg?201010220708', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Republic Swamp Speeder', set_number=8091, piece_count=176, source='Episode III', release_year=2010,
         image_url='https://images.brickset.com/sets/images/8091-1.jpg?200912120337', minifigures=['Barriss Offee', 'Battle Droid (2x)', 'Clone Trooper', 'Super Battle Droid'], set_series='Star Wars').save()
    Lego(name='Emperor Palpatine\'s Shuttle', set_number=8096, piece_count=592, source='Episode III', release_year=2010,
         image_url='https://images.brickset.com/sets/images/8096-1.jpg?201004280820', minifigures=['2-1B Medical Droid', 'Anakin Skywalker (Battle Damaged)', 'Emperor Palpatine', 'Clone Pilot'], set_series='Star Wars').save()
    Lego(name='Luke\'s Landspeeder', set_number=8092, piece_count=163, source='Episode IV', release_year=2010,
         image_url='https://images.brickset.com/sets/images/8092-1.jpg?200912210246', minifigures=['R2-D2', 'C-3PO', 'Luke Skywalker', 'Ben Kenobi', 'Sandtrooper', 'Sentry Droid'], set_series='Star Wars').save()
    Lego(name='Midi-scale Imperial Star Destroyer', set_number=8099, piece_count=423, source='Episode IV', release_year=2010,
         image_url='https://images.brickset.com/sets/images/8099-1.jpg?201006270420', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Rebel Trooper Battle Pack', set_number=8083, piece_count=79, source='Episode V', release_year=2010,
         image_url='https://images.brickset.com/sets/images/8083-1.jpg?200912120107', minifigures=['Hoth Officer', 'Hoth Rebel Trooper (2x)', 'Zev Senesca'], set_series='Star Wars').save()
    Lego(name='Snowtrooper Battle Pack', set_number=8084, piece_count=74, source='Episode V', release_year=2010,
         image_url='https://images.brickset.com/sets/images/8084-1.jpg?200912120107', minifigures=['Snowtrooper (2x)', 'AT-AT Driver', 'Imperial Officer'], set_series='Star Wars').save()
    Lego(name='Hoth Wampa Cave', set_number=8089, piece_count=297, source='Episode V', release_year=2010,
         image_url='https://images.brickset.com/sets/images/8089-1.jpg?201004280530', minifigures=['Luke Skywalker (Hoth)', 'Skeleton', 'Zev Senesca'], set_series='Star Wars').save()
    Lego(name='Slave I', set_number=8097, piece_count=573, source='Episode V', release_year=2010,
         image_url='https://images.brickset.com/sets/images/8097-1.jpg?201004280530', minifigures=['Boba Fett', 'Bossk', 'Han Solo', 'Han Solo in Carbonite'], set_series='Star Wars').save()
    Lego(name='AT-AT Walker', set_number=8129, piece_count=815, source='Episode V', release_year=2010,
         image_url='https://images.brickset.com/sets/images/8129-1.jpg?201006270420', minifigures=['AT-AT Driver', 'C-3PO', 'General Veers', 'Han Solo', 'Hoth Rebel Trooper', 'Luke Skywalker (Pilot)', 'Snowtrooper (2x)'], set_series='Star Wars').save()
    Lego(name='X-Wing Fighter', set_number=30051, piece_count=61, source='Episode V', release_year=2010,
         image_url='https://images.brickset.com/sets/images/30051-1.jpg?201002260254', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='AT-AT Walker', set_number=20018, piece_count=83, source='Episode V', release_year=2010,
         image_url='https://images.brickset.com/sets/images/20018-1.jpg?201010010343', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Imperial Shuttle', set_number=20016, piece_count=70, source='Episode VI', release_year=2010,
         image_url='https://images.brickset.com/sets/images/20016-1.jpg?201006050501', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Imperial Shuttle', set_number=10212, piece_count=2503, source='Episode VI', release_year=2010,
         image_url='https://images.brickset.com/sets/images/10212-1.jpg?201011020607', minifigures=['Darth Vader', 'Luke Skywalker (Jedi Knight)', 'Imperial Officer', 'Imperial Pilot', 'Stormtrooper'], set_series='Star Wars').save()
    Lego(name='TIE Defender', set_number=8087, piece_count=304, source='Expanded Universe', release_year=2010,
         image_url='https://images.brickset.com/sets/images/8087-1.jpg?200912120107', minifigures=['Stormtrooper', 'TIE Defender Pilot'], set_series='Star Wars').save()
    Lego(name='Freeco Speeder', set_number=8085, piece_count=177, source='Clone Wars', release_year=2010,
         image_url='https://images.brickset.com/sets/images/8085-1.jpg?200912120706', minifigures=['Anakin Skywalker (Parka)', 'Thi-Sen'], set_series='Star Wars').save()
    Lego(name='Droid Tri-Fighter', set_number=8086, piece_count=268, source='Clone Wars', release_year=2010,
         image_url='https://images.brickset.com/sets/images/8086-1.jpg?200912130333', minifigures=['Rocket Battle Droid (2x)', 'Rocket Droid Commander'], set_series='Star Wars').save()
    Lego(name='ARC-170 Starfighter', set_number=8088, piece_count=396, source='Clone Wars', release_year=2010,
         image_url='https://images.brickset.com/sets/images/8088-1.jpg?200912130333', minifigures=['Captain Jag', 'Clone Pilot', 'Kit Fisto', 'R4-P44'], set_series='Star Wars').save()
    Lego(name='Plo Koon\'s Jedi Starfighter', set_number=8093, piece_count=175, source='Clone Wars', release_year=2010,
         image_url='https://images.brickset.com/sets/images/8093-1.jpg?201004280530', minifigures=['Plo Koon', 'R7-D4'], set_series='Star Wars').save()
    Lego(name='General Grievous Starfighter', set_number=8095, piece_count=454, source='Clone Wars', release_year=2010,
         image_url='https://images.brickset.com/sets/images/8095-1.jpg?201004280530', minifigures=['EV-A4-D (2x)', 'General Grievous', 'Nahdar Vebb'], set_series='Star Wars').save()
    Lego(name='Clone Turbo Tank', set_number=8098, piece_count=1141, source='Clone Wars', release_year=2010,
         image_url='https://images.brickset.com/sets/images/8098-1.jpg?201004280530', minifigures=['Aayla Secura', 'Ahsoka Tano', 'Anakin Skywalker', 'Cad Bane', 'Clone Commander', 'Clone Trooper'], set_series='Star Wars').save()
    Lego(name='Cad Bane\'s Speeder', set_number=8128, piece_count=318, source='Clone Wars', release_year=2010,
         image_url='https://images.brickset.com/sets/images/8128-1.jpg?201005181219', minifigures=['Assassin Droid Elite', 'Cad Bane', 'Senate Commando', 'Senate Commando Captain', 'Shahan Alama'], set_series='Star Wars').save()
    Lego(name='Republic Attack Shuttle', set_number=30050, piece_count=54, source='Clone Wars', release_year=2010,
         image_url='https://images.brickset.com/sets/images/30050-1.jpg?201002260254', minifigures=['None'], set_series='Star Wars').save()

#     Lego(name='', set_number=, piece_count=, source='', release_year=2010,
#          image_url='', minifigures=['', '', ''], set_series='Star Wars').save()

def fallow(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')
    Lego.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('legos', '0007_auto_20210108_1852'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
