# Generated by Django 3.1.4 on 2021-01-13 22:01

from django.db import migrations

def seed(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')

    Lego(name='Naboo Starfighter', set_number=7877, piece_count=318, source='Episode I', release_year=2011,
         image_url='https://images.brickset.com/sets/images/7877-1.jpg?201103240413', minifigures=['Anakin Skywalker', 'Battle Droid Security (2x)', 'R2-D2', 'Droideka', 'Naboo Fighter Pilot'], set_series='Star Wars').save()
    Lego(name='The Battle of Naboo', set_number=7929, piece_count=241, source='Episode I', release_year=2011,
         image_url='https://images.brickset.com/sets/images/7929-1.jpg?201012221109', minifigures=['Battle Droid Pilot (2x)', 'Battle Droid (8x)', 'Gungan Soldier', 'Jar Jar Binks'], set_series='Star Wars').save()
    Lego(name='Darth Maul\'s Sith Infiltrator', set_number=7961, piece_count=479, source='Episode I', release_year=2011,
         image_url='https://images.brickset.com/sets/images/7961-1.jpg?201102131044', minifigures=['Darth Maul', 'Qui-Gon Jinn', 'Padme Amidala', 'Captain Panaka'], set_series='Star Wars').save()
    Lego(name='Anakin\'s and Sebulba\'s Podracer', set_number=7962, piece_count=810, source='Episode I', release_year=2011,
         image_url='https://images.brickset.com/sets/images/7962-1.jpg?201102131044', minifigures=['Anakin Skywalker', 'Obi-Wan Kenobi', 'Sebulba', 'Wald', 'Watto'], set_series='Star Wars').save()
    Lego(name='Mini AAT', set_number=30052, piece_count=46, source='Episode I', release_year=2011,
         image_url='https://images.brickset.com/sets/images/30052-1.jpg?201101011101', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Mini Vulture Droid', set_number=30055, piece_count=45, source='Episode I', release_year=2011,
         image_url='https://images.brickset.com/sets/images/30055-1.jpg?201103040847', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Mini Republic Attack Cruiser', set_number=30053, piece_count=41, source='Episode III', release_year=2011,
         image_url='https://images.brickset.com/sets/images/30053-1.jpg?201101011101', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Millennium Falcon', set_number=7965, piece_count=1254, source='Episode IV', release_year=2011,
         image_url='https://images.brickset.com/sets/images/7965-1.jpg?201102131044', minifigures=['Darth Vader', 'Obi-Wan Kenobi', 'Han Solo', 'Chewbacca', 'Luke Skywalker', 'Princess Leia'], set_series='Star Wars').save()
    Lego(name='UCS Super Star Destroyer', set_number=10221, piece_count=3152, source='Episode V', release_year=2011,
         image_url='https://images.brickset.com/sets/images/10221-1.jpg?201104120227', minifigures=['Darth Vader', 'Dengar', 'IG-88', 'Bossk', 'Admiral Piett'], set_series='Star Wars').save()
    Lego(name='Hoth Echo base', set_number=7879, piece_count=773, source='Episode V', release_year=2011,
         image_url='https://images.brickset.com/sets/images/7879-1.jpg?201106010207', minifigures=['2-1B Medical Droid', 'Chewbacca', 'Han Solo (Parka)', 'Luke Skywalker (Bacta Tank)', 'Princess Leia (Hoth)', 'R-3PO', 'Snowtrooper (2x)'], set_series='Star Wars').save()
    Lego(name='Mini Slave I', set_number=20019, piece_count=76, source='Episode V', release_year=2011,
         image_url='https://images.brickset.com/sets/images/20019-1.jpg?201012300825', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Ewok Attack', set_number=7956, piece_count=166, source='Episode VI', release_year=2011,
         image_url='https://images.brickset.com/sets/images/7956-1.jpg?201102131044', minifigures=['Logray (Ewok)', 'Tokkat (Ewok)', 'Scout Trooper'], set_series='Star Wars').save()
    Lego(name='Mini AT-ST', set_number=30054, piece_count=46, source='Episode VI', release_year=2011,
         image_url='https://images.brickset.com/sets/images/30054-1.jpg?201103030240', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Advent Calendar', set_number=7958, piece_count=266, source='Expanded Universe', release_year=2011,
         image_url='https://images.brickset.com/sets/images/7958-1.jpg?201605181105', minifigures=['Battle Droid Pilot', 'Chewbacca', 'Clone Pilot', 'Mouse Droid', 'Nute Gunray', 'R2-Q5', 'Yoda (Santa)', 'TIE Defender Pilot', 'Zev Senesca'], set_series='Star Wars').save()
    Lego(name='Imperial V-Wing Starfighter', set_number=7915, piece_count=139, source='Expanded Universe', release_year=2011,
         image_url='https://images.brickset.com/sets/images/7915-1.jpg?201012221108', minifigures=['Imperial V-Wing Pilot', 'R2-Q2'], set_series='Star Wars').save()
    Lego(name='Mace Windu\'s Jedi Starfighter', set_number=7868, piece_count=313, source='Clone Wars', release_year=2011,
         image_url='https://images.brickset.com/sets/images/7868-1.jpg?201012170346', minifigures=['Mace Windu', 'Battle Droid (2x)', 'R8-B7', 'TX-20 (Tactical Droid)'], set_series='Star Wars').save()
    Lego(name='Battle For Geonosis', set_number=7869, piece_count=331, source='Clone Wars', release_year=2011,
         image_url='https://images.brickset.com/sets/images/7869-1.jpg?201012221107', minifigures=['Battle Droid (2x)', 'Captain Rex', 'Luminara Unduli', 'Super Battle Droid'], set_series='Star Wars').save()
    Lego(name='Clone Trooper Battle Pack', set_number=7913, piece_count=85, source='Clone Wars', release_year=2011,
         image_url='https://images.brickset.com/sets/images/7913-1.jpg?201012230326', minifigures=['ARF Trooper', 'Bomb Squad Trooper (2x)', 'Clone Trooper (Sand Green Markings)'], set_series='Star Wars').save()
    Lego(name='Mandalorian Battle Pack', set_number=7914, piece_count=68, source='Clone Wars', release_year=2011,
         image_url='https://images.brickset.com/sets/images/7914-1.jpg?201012230326', minifigures=['Mandalorian Death Watch Warriors (4x)'], set_series='Star Wars').save()
    Lego(name='Mini Bounty Hunter Assault Gunship', set_number=20021, piece_count=81, source='Clone Wars', release_year=2011,
         image_url='https://images.brickset.com/sets/images/20021-1.jpg?201104020822', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Bounty Hunter Assault Gunship', set_number=7930, piece_count=389, source='Clone Wars', release_year=2011,
         image_url='https://images.brickset.com/sets/images/7930-1.jpg?201012230325', minifigures=['Assassin Droid Elite', 'Aurra Sing', 'Embo', 'Sugi'], set_series='Star Wars').save()
    Lego(name='T-6 Jedi Shuttle', set_number=7931, piece_count=389, source='Clone Wars', release_year=2011,
         image_url='https://images.brickset.com/sets/images/7931-1.jpg?201012230324', minifigures=['Obi-Wan Kenobi', 'Anakin Skywalker', 'Shaak Ti', 'Saesee Tiin'], set_series='Star Wars').save()
    Lego(name='Sith Nightspeeder', set_number=7957, piece_count=214, source='Clone Wars', release_year=2011,
         image_url='https://images.brickset.com/sets/images/7957-1.jpg?201102131044', minifigures=['Anakin Skywalker', 'Asajj Ventress', 'Savage Opress'], set_series='Star Wars').save()
    Lego(name='Geonosian Starfighter', set_number=7959, piece_count=155, source='Clone Wars', release_year=2011,
         image_url='https://images.brickset.com/sets/images/7959-1.jpg?201102131044', minifigures=['Ki-Adi-Mundi', 'Commander Cody', 'Geonosian'], set_series='Star Wars').save()
    Lego(name='Republic Frigate', set_number=7964, piece_count=1015, source='Clone Wars', release_year=2011,
         image_url='https://images.brickset.com/sets/images/7964-1.jpg?201102131044', minifigures=['Yoda', 'Commander Wolffe', 'Eeth Koth', 'Quinlan Vos', 'Wolfpack Clone Trooper'], set_series='Star Wars').save()

    # Lego(name='', set_number=, piece_count=, source='', release_year=2011,
    #      image_url='', minifigures=['', '', ''], set_series='Star Wars').save()

def fallow(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')
    Lego.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('legos', '0008_auto_20210111_2133'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
