# Generated by Django 3.1.4 on 2021-01-14 20:49

from django.db import migrations


def seed(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')

    Lego(name='Gungan Sub', set_number=9499, piece_count=465, source='Episode I', release_year=2012,
         image_url='https://images.brickset.com/sets/images/9499-1.jpg?201205010252', minifigures=['Jar Jar Binks', 'Qui-Gon Jinn', 'Obi-Wan Kenobi', 'Queen Amidala'], set_series='Star Wars').save()
    Lego(name='Planet Set: Naboo Starfighter and Naboo', set_number=9674, piece_count=56, source='Episode I', release_year=2012,
         image_url='https://images.brickset.com/sets/images/9674-1.jpg?201111200229', minifigures=['Naboo Fighter Pilot'], set_series='Star Wars').save()
    Lego(name='Planet Set: Sebulba\'s Podracer and Tatooine', set_number=9675, piece_count=80, source='Episode I', release_year=2012,
         image_url='https://images.brickset.com/sets/images/9675-1.jpg?201111200229', minifigures=['Sebulba'], set_series='Star Wars').save()
    Lego(name='UCS R2-D2', set_number=10225, piece_count=2127, source='Episode I', release_year=2012,
         image_url='https://images.brickset.com/sets/images/10225-1.jpg?201201160156', minifigures=['R2-D2'], set_series='Star Wars').save()
    Lego(name='Mini Anakin\'s Podracer', set_number=30057, piece_count=38, source='Episode I', release_year=2012,
         image_url='https://images.brickset.com/sets/images/30057-1.jpg?201201010705', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Mini MTT', set_number=30059, piece_count=51, source='Episode I', release_year=2012,
         image_url='https://images.brickset.com/sets/images/30059-1.jpg?201201010705', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Mini STAP', set_number=30058, piece_count=24, source='Episode I', release_year=2012,
         image_url='https://images.brickset.com/sets/images/30058-1.jpg?201112291106', minifigures=['Battle Droid'], set_series='Star Wars').save()
    Lego(name='Anakin\'s Jedi Interceptor', set_number=9494, piece_count=300, source='Episode III', release_year=2012,
         image_url='https://images.brickset.com/sets/images/9494-1.jpg?201110150700', minifigures=['Anakin Skywalker', 'Obi-Wan Kenobi', 'Battle Droid Security', 'R2-D2', 'Nute Gunray'], set_series='Star Wars').save()
    Lego(name='Palpatine\'s Arrest', set_number=9526, piece_count=645, source='Episode III', release_year=2012,
         image_url='https://images.brickset.com/sets/images/9526-1.jpg?201205291215', minifigures=['Agen Kolar', 'Anakin Skywalker', 'Chancellor Palpatine', 'Kit Fisto', 'Mace Windu', 'Saesee Tiin'], set_series='Star Wars').save()
    Lego(name='Droid Escape', set_number=9490, piece_count=137, source='Episode IV', release_year=2012,
         image_url='https://images.brickset.com/sets/images/9490-1.jpg?201110150700', minifigures=['Sandtrooper (2x)', 'R2-D2', 'C-3PO'], set_series='Star Wars').save()
    Lego(name='TIE Fighter', set_number=9492, piece_count=413, source='Episode IV', release_year=2012,
         image_url='https://images.brickset.com/sets/images/9492-1.jpg?201110150700', minifigures=['Death Star Trooper', 'Imperial Officer', 'R5-J2', 'TIE Fighter Pilot'], set_series='Star Wars').save()
    Lego(name='X-Wing Starfighter', set_number=9493, piece_count=560, source='Episode IV', release_year=2012,
         image_url='https://images.brickset.com/sets/images/9493-1.jpg?201110150700', minifigures=['R2-D2', 'Luke Skywalker (Pilot)', 'Jek Porkins', 'R5-D8'], set_series='Star Wars').save()
    Lego(name='Gold Leader\'s Y-Wing Starfighter', set_number=9495, piece_count=458, source='Episode IV', release_year=2012,
         image_url='https://images.brickset.com/sets/images/9495-1.jpg?201110170336', minifigures=['Princess Leia', 'R5-F7', 'Dutch Vander'], set_series='Star Wars').save()
    Lego(name='Planet Set: TIE Interceptor and Death Star', set_number=9676, piece_count=65, source='Episode IV', release_year=2012,
         image_url='https://images.brickset.com/sets/images/9676-1.jpg?201111200229', minifigures=['TIE Fighter Pilot'], set_series='Star Wars').save()
    Lego(name='Mini Star Destroyer', set_number=30056, piece_count=38, source='Episode IV', release_year=2012,
         image_url='https://images.brickset.com/sets/images/30056-1.jpg?201112291105', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Planet Set: X-Wing Starfighter and Yavin 4', set_number=9677, piece_count=77, source='Episode IV', release_year=2012,
         image_url='https://images.brickset.com/sets/images/9677-1.jpg?201205010135', minifigures=['X-Wing Pilot'], set_series='Star Wars').save()
    Lego(name='LEGO Games: The Battle of Hoth', set_number=3866, piece_count=305, source='Episode V', release_year=2012,
         image_url='https://images.brickset.com/sets/images/3866-1.jpg?201109141049', minifigures=['Microfigure AT-ST Pilot', 'Microfigure Boba Fett', 'Microfigure Chewbacca', 'Microfigure Darth Vader', 'Microfigure General Veers', 'Microfigure Han Solo', 'Microfigure Luke Skywalker', 'Microfigure Rebel Pilot (4x)', 'Microfigure Rebel Trooper (9x)', 'Microfigure Snowtrooper (12x)'], set_series='Star Wars').save()
    Lego(name='Planet Set: Twin-Pod Cloud Car and Bespin', set_number=9678, piece_count=78, source='Episode V', release_year=2012,
         image_url='https://images.brickset.com/sets/images/9678-1.jpg?201205010135', minifigures=['Lobot'], set_series='Star Wars').save()
    Lego(name='Endor Rebel Trooper & Imperial Battle Pack', set_number=9489, piece_count=77, source='Episode VI', release_year=2012,
         image_url='https://images.brickset.com/sets/images/9489-1.jpg?201110150700', minifigures=['Scout Trooper', 'Endor Rebel Commando (2x)', 'Stormtrooper'], set_series='Star Wars').save()
    Lego(name='Desert Skiff', set_number=9496, piece_count=213, source='Episode VI', release_year=2012,
         image_url='https://images.brickset.com/sets/images/9496-1.jpg?201205010252', minifigures=['Luke Skywalker (Jedi Knight)', 'Boba Fett', 'Kithaba', 'Lando Calrissian (Guard Disguise)'], set_series='Star Wars').save()
    Lego(name='Jabba\'s Palace', set_number=9516, piece_count=717, source='Episode VI', release_year=2012,
         image_url='https://images.brickset.com/sets/images/9516-1.jpg?201205010252', minifigures=['B\'Omarr Monk', 'Bib Fortuna', 'Boushh', 'Chewbacca', 'Gamorrean Guard', 'Han Solo in Carbonite', 'Han Solo', 'Jabba the Hutt', 'Oola', 'Salacious B. Crumb'], set_series='Star Wars').save()
    Lego(name='Planet Set: AT-ST and Endor', set_number=9679, piece_count=65, source='Episode VI', release_year=2012,
         image_url='https://images.brickset.com/sets/images/9679-1.jpg?201205010135', minifigures=['AT-ST Driver'], set_series='Star Wars').save()
    Lego(name='B-Wing Starfighter', set_number=10227, piece_count=1487, source='Episode VI', release_year=2012,
         image_url='https://images.brickset.com/sets/images/10227-1.jpg?201201160157', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='Sith Fury Class Interceptor', set_number=9500, piece_count=741, source='Expanded Universe', release_year=2012,
         image_url='https://images.brickset.com/sets/images/9500-1.jpg?201205010252', minifigures=['Darth Malgus', 'Sith Trooper (2x)'], set_series='Star Wars').save()
    Lego(name='Advent Calendar', set_number=9509, piece_count=234, source='Expanded Universe', release_year=2012,
         image_url='https://images.brickset.com/sets/images/9509-1.jpg?201605181111', minifigures=['Battle Droid Security', 'Gonk Droid', 'Gungan Soldier', 'Hoth Rebel trooper', 'Imperial Officer', 'R2-D2 (Snowman)', 'Rebel Fleet Trooper', 'Darth Maul (Santa)', 'Snowtrooper', 'Super Battle Droid'], set_series='Star Wars').save()
    Lego(name='Republic Striker-class Starfighter', set_number=9497, piece_count=376, source='Expanded Universe', release_year=2012,
         image_url='https://images.brickset.com/sets/images/9497-1.jpg?201205010252', minifigures=['Jace Malcom', 'Satele Shan', 'T7-O1'], set_series='Star Wars').save()
    Lego(name='Geonosian Cannon', set_number=9491, piece_count=132, source='Clone Wars', release_year=2012,
         image_url='https://images.brickset.com/sets/images/9491-1.jpg?201110221038', minifigures=['Barriss Offee', 'Clone Commander Gree', 'Geonosian Warrior', 'Geonosian Zombie'], set_series='Star Wars').save()
    Lego(name='Elite Clone Trooper & Commmando Droid Battle Pack', set_number=9488, piece_count=98, source='Clone Wars', release_year=2012,
         image_url='https://images.brickset.com/sets/images/9488-1.jpg?201110150700', minifigures=['ARC Trooper', 'ARF Trooper', 'Commando Droid (2x)'], set_series='Star Wars').save()
    Lego(name='Saesee Tiin\'s Jedi Starfighter', set_number=9498, piece_count=244, source='Clone Wars', release_year=2012,
         image_url='https://images.brickset.com/sets/images/9498-1.jpg?201205010252', minifigures=['Even Piell', 'R3-D5', 'Saesee Tiin'], set_series='Star Wars').save()
    Lego(name='The Malevolence', set_number=9515, piece_count=1092, source='Clone Wars', release_year=2012,
         image_url='https://images.brickset.com/sets/images/9515-1.jpg?201205010252', minifigures=['General Grievous', 'Anakin Skywalker', 'Padme Amidala', 'Battle Droid Commander', 'Battle Droid', 'Count Dooku'], set_series='Star Wars').save()
    Lego(name='Pre Vizsla\'s Mandalorian Fighter', set_number=9525, piece_count=403, source='Clone Wars', release_year=2012,
         image_url='https://images.brickset.com/sets/images/9525-1.jpg?201205110641', minifigures=['Obi-Wan Kenobi', 'Mandalorian Death Watch Warrior', 'Pre Vizsla'], set_series='Star Wars').save()

#     Lego(name='', set_number=, piece_count=, source='', release_year=2011,
#          image_url='', minifigures=['', '', ''], set_series='Star Wars').save()

def fallow(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')
    Lego.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('legos', '0009_auto_20210113_2201'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
