# Generated by Django 3.1.4 on 2021-01-15 18:45

from django.db import migrations


def seed(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')

    Lego(name='Clone Troopers vs Droidekas', set_number=75000, piece_count=124, source='Episode II', release_year=2013,
         image_url='https://images.brickset.com/sets/images/75000-1.jpg?201210180459', minifigures=['Droideka (2x)', 'Clone Trooper', 'Clone Sergeant'], set_series='Star Wars').save()
    Lego(name='Jedi Starfighter & Planet Kamino', set_number=75006, piece_count=61, source='Episode II', release_year=2013,
         image_url='https://images.brickset.com/sets/images/75006-1.jpg?201210200814', minifigures=['R4-P17'], set_series='Star Wars').save()
    Lego(name='Corporate Alliance Tank Droid', set_number=75015, piece_count=271, source='Episode II', release_year=2013,
         image_url='https://images.brickset.com/sets/images/75015-1.jpg?201302101020', minifigures=['Jango Fett', 'Clone Trooper', 'Battle Droid'], set_series='Star Wars').save()
    Lego(name='Homing Spider Droid', set_number=75016, piece_count=295, source='Episode II', release_year=2013,
         image_url='https://images.brickset.com/sets/images/75016-1.jpg?201302110344', minifigures=['Clone Trooper', 'Dwarf Spider Droid', 'Stass Allie', 'Super Battle Droid (2x)'], set_series='Star Wars').save()
    Lego(name='Duel On Geonosis', set_number=75017, piece_count=391, source='Episode II', release_year=2013,
         image_url='https://images.brickset.com/sets/images/75017-1.jpg?201302101020', minifigures=['Count Dooku', 'FA-4 Pilot Droid', 'Poggle the Lesser', 'Yoda'], set_series='Star Wars').save()
    Lego(name='AT-TE', set_number=75019, piece_count=794, source='Episode II', release_year=2013,
         image_url='https://images.brickset.com/sets/images/75019-1.jpg?201302101020', minifigures=['Mace Windu', 'Coleman Trebor', 'Clone Commander', 'Battle Droid', 'Battle Droid Commander'], set_series='Star Wars').save()
    Lego(name='Republic Gunship', set_number=75021, piece_count=1175, source='Episode II', release_year=2013,
         image_url='https://images.brickset.com/sets/images/75021-1.jpg?201302101020', minifigures=['Padme Amidala', 'Anakin Skywalker', 'Obi-Wan Kenobi', 'Super Battle Droid (2x)', 'Clone Pilot', 'Clone Captain'], set_series='Star Wars').save()
    Lego(name='Republic Assault Ship & Coruscant', set_number=75007, piece_count=74, source='Episode III', release_year=2013,
         image_url='https://images.brickset.com/sets/images/75007-1.jpg?201210201045', minifigures=['Clone Trooper'], set_series='Star Wars').save()
    Lego(name='Tantive IV & Alderaan', set_number=75011, piece_count=102, source='Episode IV', release_year=2013,
         image_url='https://images.brickset.com/sets/images/75011-1.jpg?201210201045', minifigures=['Rebel Fleet Trooper'], set_series='Star Wars').save()
    Lego(name='Red Five X-Wing Starfighter', set_number=10240, piece_count=1559, source='Episode IV', release_year=2013,
         image_url='https://images.brickset.com/sets/images/10240-1.jpg?201510140806', minifigures=['R2-D2'], set_series='Star Wars').save()
    Lego(name='TIE Bomber & Asteroid Field', set_number=75008, piece_count=60, source='Episode V', release_year=2013,
         image_url='https://images.brickset.com/sets/images/75008-1.jpg?201210201045', minifigures=['TIE Pilot'], set_series='Star Wars').save()
    Lego(name='Snowspeeder & Hoth', set_number=75009, piece_count=69, source='Episode V', release_year=2013,
         image_url='https://images.brickset.com/sets/images/75009-1.jpg?201210211056', minifigures=['Snowspeeder Pilot'], set_series='Star Wars').save()
    Lego(name='Battle of Hoth', set_number=75014, piece_count=426, source='Episode V', release_year=2013,
         image_url='https://images.brickset.com/sets/images/75014-1.jpg?201211280323', minifigures=['Snowtrooper (2x)', 'Hoth Rebel trooper (2x)', 'General Rieekan', 'Luke Skywalker', 'Imperial Probe Droid'], set_series='Star Wars').save()
    Lego(name='Ewok Village', set_number=10236, piece_count=1990, source='Episode VI', release_year=2013,
         image_url='https://images.brickset.com/sets/images/10236-1.jpg?201605160204', minifigures=['C-3PO', 'Chewbacca', 'Chief Chirpa (Ewok)', 'Endor Rebel Commando (2x)', 'Ewok Warrior', 'Han Solo', 'Logray (Ewok)', 'Luke Skywalker (Jedi Master)', 'Princess Leia', 'R2-D2', 'Scout Trooper (2x)', 'Stormtrooper (2x)', 'Teebo (Ewok)', 'Wicket (Ewok)'], set_series='Star Wars').save()
    Lego(name='A-Wing Starfighter', set_number=75003, piece_count=177, source='Episode VI', release_year=2013,
         image_url='https://images.brickset.com/sets/images/75003-1.jpg?201210180459', minifigures=['Admiral Ackbar', 'Han Solo', 'Rebel A-Wing Pilot'], set_series='Star Wars').save()
    Lego(name='Rancor Pit', set_number=75005, piece_count=380, source='Episode VI', release_year=2013,
         image_url='https://images.brickset.com/sets/images/75005-1.jpg?201209170440', minifigures=['Luke Skywalker (Jedi Knight)', 'Gamorrean Guard', 'Malakili'], set_series='Star Wars').save()
    Lego(name='B-Wing Starfighter & Endor', set_number=75010, piece_count=83, source='Episode VI', release_year=2013,
         image_url='https://images.brickset.com/sets/images/75010-1.jpg?201210211056', minifigures=['Rebel B-Wing Pilot'], set_series='Star Wars').save()
    Lego(name='Jabba\'s Sail Barge', set_number=75020, piece_count=850, source='Episode VI', release_year=2013,
         image_url='https://images.brickset.com/sets/images/75020-1.jpg?201302101020', minifigures=['Jabba the Hutt', 'Max Rebo', 'Princess Leia', 'R2-D2 (Serving Tray)', 'Ree-Yees', 'Weequay Skiff Guard'], set_series='Star Wars').save()
    Lego(name='Republic Trooper vs Sith Troopers', set_number=75001, piece_count=63, source='Expanded Universe', release_year=2013,
         image_url='https://images.brickset.com/sets/images/75001-1.jpg?201210180459', minifigures=['Republic Trooper (2x)', 'Sith Trooper (2x)'], set_series='Star Wars').save()
    Lego(name='JEK-14\'s Stealth Starfighter', set_number=75018, piece_count=550, source='Expanded Universe', release_year=2013,
             image_url='https://images.brickset.com/sets/images/75018-1.jpg?201302101020', minifigures=['Bounty Hunter', 'Jek-14', 'R4-G0', 'Special Forces Clone Trooper'], set_series='Star Wars').save()
    Lego(name='Advent Calendar', set_number=75023, piece_count=254, source='Expanded Universe', release_year=2013,
             image_url='https://images.brickset.com/sets/images/75023-1.jpg?201302101020', minifigures=['Battle Droid', 'Boba Fett (Young)', 'Clone Trooper', 'Endor Rebel Trooper', 'FA-4 Pilot Droid', 'Geonosian', 'R5-F7', 'Jango Fett (Santa)', 'Scout Trooper'], set_series='Star Wars').save()
    Lego(name='Jedi Defender-Class Cruiser', set_number=75025, piece_count=927, source='Expanded Universe', release_year=2013,
             image_url='https://images.brickset.com/sets/images/75025-1.jpg?201212280421', minifigures=['Jedi Consular', 'Jedi Knight', 'Sith Trooper', 'Sith Warrior'], set_series='Star Wars').save()
    Lego(name='AT-RT', set_number=75002, piece_count=222, source='Clone Wars', release_year=2013,
             image_url='https://images.brickset.com/sets/images/75002-1.jpg?201210180459', minifigures=['Yoda', 'Droideka', 'Commando Droid Captain', '501st Legion CLone Trooper'], set_series='Star Wars').save()
    Lego(name='Z-95 Headhunter', set_number=75004, piece_count=373, source='Clone Wars', release_year=2013,
             image_url='https://images.brickset.com/sets/images/75004-1.jpg?201210180459', minifigures=['Pong Krell', '501st Clone Pilot', '501st Legion Clone Trooper'], set_series='Star Wars').save()
    Lego(name='BARC Speeder with Sidecar', set_number=75012, piece_count=226, source='Clone Wars', release_year=2013,
             image_url='https://images.brickset.com/sets/images/75012-1.jpg?201210180459', minifigures=['Captain Rex', 'Commando Droid (2x)', 'Obi-Wan Kenobi'], set_series='Star Wars').save()
    Lego(name='Umbaran MHC (Mobile Heavy Cannon)', set_number=75013, piece_count=493, source='Clone Wars', release_year=2013,
             image_url='https://images.brickset.com/sets/images/75013-1.jpg?201210180459', minifigures=['Ahsoka Tano', '212th Clone Trooper', 'Umbaran Soldier (2x)'], set_series='Star Wars').save()
    Lego(name='Mandalorian Speeder', set_number=75022, piece_count=211, source='Clone Wars', release_year=2013,
             image_url='https://images.brickset.com/sets/images/75022-1.jpg?201302101020', minifigures=['Darth Maul (Mech Legs)', 'Mandalorian Super Commando (2x)'], set_series='Star Wars').save()
    Lego(name='HH-87 Starhopper', set_number=75024, piece_count=362, source='Clone Wars', release_year=2013,
             image_url='https://images.brickset.com/sets/images/75024-1.jpg?201305020417', minifigures=['Cad Bane', 'Nikto Guard', 'Obi-Wan Kenobi (Rako Hardeen)'], set_series='Star Wars').save()
    Lego(name='Z-95 Headhunter', set_number=30240, piece_count=54, source='Clone Wars', release_year=2013,
             image_url='https://images.brickset.com/sets/images/30240-1.jpg?201301030530', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Mandalorian Fighter', set_number=30241, piece_count=49, source='Clone Wars', release_year=2013,
             image_url='https://images.brickset.com/sets/images/30241-1.jpg?201301030530', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Republic Frigate', set_number=30242, piece_count=45, source='Clone Wars', release_year=2013,
             image_url='https://images.brickset.com/sets/images/30242-1.jpg?201301030530', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Umbaran MHC', set_number=30243, piece_count=48, source='Clone Wars', release_year=2013,
             image_url='https://images.brickset.com/sets/images/30243-1.jpg?201301030530', minifigures=['None'], set_series='Star Wars').save()

#     Lego(name='', set_number=, piece_count=, source='', release_year=2013,
#          image_url='', minifigures=['', '', ''], set_series='Star Wars').save()


def fallow(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')
    Lego.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('legos', '0010_auto_20210114_2049'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
