# Generated by Django 3.1.4 on 2021-01-18 18:50

from django.db import migrations


def seed(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')

    Lego(name='AAT', set_number=75029, piece_count=95, source='Episode I', release_year=2014,
         image_url='https://images.brickset.com/sets/images/75029-1.jpg?201311210953', minifigures=['Battle Droid Pilot'], set_series='Star Wars').save()
    Lego(name='Anakin\'s Jedi Interceptor', set_number=30244, piece_count=45, source='Episode III', release_year=2014,
         image_url='https://images.brickset.com/sets/images/30244-1.jpg?201401021018', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='ARC-170 Starfighter', set_number=30247, piece_count=54, source='Episode III', release_year=2014,
         image_url='https://images.brickset.com/sets/images/30247-1.jpg?201401021018', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Clone Turbo Tank', set_number=75028, piece_count=96, source='Episode III', release_year=2014,
         image_url='https://images.brickset.com/sets/images/75028-1.jpg?201311210953', minifigures=['Clone Trooper'], set_series='Star Wars').save()
    Lego(name='Kashyyyk Troopers', set_number=75035, piece_count=99, source='Episode III', release_year=2014,
         image_url='https://images.brickset.com/sets/images/75035-1.jpg?201311131110', minifigures=['41st Elite Corps Trooper (2x)', '41st Kashyyyk Clone Trooper'], set_series='Star Wars').save()
    Lego(name='Utapau Troopers', set_number=75036, piece_count=83, source='Episode III', release_year=2014,
         image_url='https://images.brickset.com/sets/images/75036-1.jpg?201311131110', minifigures=['212th Battalion Trooper (2x)', 'Airborne Clone Trooper (2x)'], set_series='Star Wars').save()
    Lego(name='Battle on Saleucami', set_number=75037, piece_count=183, source='Episode III', release_year=2014,
         image_url='https://images.brickset.com/sets/images/75037-1.jpg?201311131110', minifigures=['BARC Trooper', 'Battle Droid (2x)', 'Super Battle Droid (2x)'], set_series='Star Wars').save()
    Lego(name='Jedi Interceptor', set_number=75038, piece_count=223, source='Episode III', release_year=2014,
         image_url='https://images.brickset.com/sets/images/75038-1.jpg?201311131110', minifigures=['Anakin Skywalker', 'R2-D2'], set_series='Star Wars').save()
    Lego(name='General Grievous\' Wheel Bike', set_number=75040, piece_count=261, source='Episode III', release_year=2014,
         image_url='https://images.brickset.com/sets/images/75040-1.jpg?201311131110', minifigures=['Obi-Wan Kenobi', 'General Grievous'], set_series='Star Wars').save()
    Lego(name='V-Wing Starfighter', set_number=75039, piece_count=201, source='Episode III', release_year=2014,
         image_url='https://images.brickset.com/sets/images/75039-1.jpg?201311131110', minifigures=['Astromech Droid', 'V-Wing Pilot'], set_series='Star Wars').save()
    Lego(name='Vulture Droid', set_number=75041, piece_count=205, source='Episode III', release_year=2014,
         image_url='https://images.brickset.com/sets/images/75041-1.jpg?201311131110', minifigures=['Buzz Droid', 'Battle Droid Pilot', 'Neimoidian Warrior'], set_series='Star Wars').save()
    Lego(name='Droid Gunship', set_number=75042, piece_count=439, source='Episode III', release_year=2014,
         image_url='https://images.brickset.com/sets/images/75042-1.jpg?201311020432', minifigures=['41st Elite Corps Trooper', 'Chewbacca', 'Battle Droid', 'Super Battle Droid'], set_series='Star Wars').save()
    Lego(name='AT-AP', set_number=75043, piece_count=717, source='Episode III', release_year=2014,
         image_url='https://images.brickset.com/sets/images/75043-1.jpg?201308150353', minifigures=['Battle Droid', 'Battle Droid Commander', 'Chief Tarfful', 'Clone Commander Gree', 'Super Battle Droid'], set_series='Star Wars').save()
    Lego(name='Droid Tri-Fighter', set_number=75044, piece_count=262, source='Episode III', release_year=2014,
         image_url='https://images.brickset.com/sets/images/75044-1.jpg?201311210943', minifigures=['Buzz Droid', 'Battle Droid Security', 'Battle Droid', 'Chancellor Palpatine'], set_series='Star Wars').save()
    Lego(name='Millennium Falcon', set_number=75030, piece_count=94, source='Episode IV', release_year=2014,
         image_url='https://images.brickset.com/sets/images/75030-1.jpg?201311210953', minifigures=['Han Solo'], set_series='Star Wars').save()
    Lego(name='X-Wing Fighter', set_number=75032, piece_count=97, source='Episode IV', release_year=2014,
         image_url='https://images.brickset.com/sets/images/75032-1.jpg?201311210953', minifigures=['Rebel X-Wing Pilot'], set_series='Star Wars').save()
    Lego(name='Star Destroyer', set_number=75033, piece_count=97, source='Episode IV', release_year=2014,
         image_url='https://images.brickset.com/sets/images/75033-1.jpg?201311210953', minifigures=['Imperial Crew'], set_series='Star Wars').save()
    Lego(name='Death Star Troopers', set_number=75034, piece_count=102, source='Episode IV', release_year=2014,
         image_url='https://images.brickset.com/sets/images/75034-1.jpg?201311131110', minifigures=['Royal Guard (2x)', 'Imperial Gunner (2x)'], set_series='Star Wars').save()
    Lego(name='Star Destroyer', set_number=75055, piece_count=1359, source='Episode IV', release_year=2014,
         image_url='https://images.brickset.com/sets/images/75055-1.jpg?201402170929', minifigures=['Darth Vader', 'Imperial Crew', 'Imperial Navy Trooper', 'Imperial Officer', 'Mouse Droid', 'Stormtrooper (2x)'], set_series='Star Wars').save()
    Lego(name='Mos Eisley Cantina', set_number=75052, piece_count=615, source='Episode IV', release_year=2014,
         image_url='https://images.brickset.com/sets/images/75052-1.jpg?201402170929', minifigures=['Bith Musician (3x)', 'Greedo', 'Han Solo', 'Luke Skywalker', 'Ben Kenobi', 'Sandtrooper'], set_series='Star Wars').save()
    Lego(name='Sandcrawler', set_number=75059, piece_count=3296, source='Episode IV', release_year=2014,
         image_url='https://images.brickset.com/sets/images/75059-1.jpg?201403080812', minifigures=['Luke Skywalker', 'C-3PO', 'Gonk Droid', 'Jawa (4x)', 'Mini Treadwell Droid', 'Owen Lars', 'R1-Series Droid', 'R2 Unit', 'R2-D2', 'R5-D8', 'Treadwell Droid'], set_series='Star Wars').save()
    Lego(name='AT-AT', set_number=75054, piece_count=1137, source='Episode V', release_year=2014,
         image_url='https://images.brickset.com/sets/images/75054-1.jpg?201402170929', minifigures=['AT-AT Driver', 'General Veers', 'Snowtrooper Commander', 'Snowtrooper (2x)'], set_series='Star Wars').save()
    Lego(name='Imperial Shuttle', set_number=30246, piece_count=57, source='Episode VI', release_year=2014,
         image_url='https://images.brickset.com/sets/images/30246-1.jpg?201401021018', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='TIE Interceptor', set_number=75031, piece_count=92, source='Episode VI', release_year=2014,
         image_url='https://images.brickset.com/sets/images/75031-1.jpg?201311210953', minifigures=['TIE Pilot'], set_series='Star Wars').save()
    Lego(name='Republic AV-7 Anti-Vehicle Cannon', set_number=75045, piece_count=434, source='Clone Wars', release_year=2014,
         image_url='https://images.brickset.com/sets/images/75045-1.jpg?201311131111', minifigures=['Droideka', 'Plo Koon', 'Wolfpack Clone Trooper (2x)'], set_series='Star Wars').save()
    Lego(name='Coruscant Police Gunship', set_number=75046, piece_count=481, source='Clone Wars', release_year=2014,
         image_url='https://images.brickset.com/sets/images/75046-1.jpg?201311210943', minifigures=['Anakin Skywalker', 'Ahsoka Tano', 'Shock Trooper (2x)'], set_series='Star Wars').save()

    # Lego(name='', set_number=, piece_count=, source='', release_year=2014,
    #      image_url='', minifigures=['', '', ''], set_series='Star Wars').save()


def fallow(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')
    Lego.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('legos', '0011_auto_20210115_1845'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
