# Generated by Django 3.1.4 on 2021-01-19 20:23

from django.db import migrations


def seed(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')

    Lego(name='A-Wing Starfighter', set_number=30272, piece_count=58, source='Episode VI', release_year=2015,
         image_url='https://images.brickset.com/sets/images/30272-1.jpg?201510151032', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='AT-DP', set_number=30274, piece_count=65, source='Rebels', release_year=2015,
         image_url='https://images.brickset.com/sets/images/30274-1.jpg?201510151032', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='TIE Advanced Prototype', set_number=30275, piece_count=47, source='Rebels', release_year=2015,
         image_url='https://images.brickset.com/sets/images/30275-1.jpg?201510151032', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='First Order Special Forces TIE Fighter', set_number=30276, piece_count=41, source='Episode VII', release_year=2015,
         image_url='https://images.brickset.com/sets/images/30276-1.jpg?201510151032', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Battle Pack 2 in 1', set_number=66535, piece_count=83, source='Episode III', release_year=2015,
         image_url='https://images.brickset.com/sets/images/66535-1.jpg?201511070947', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Battle Pack 2 in 1', set_number=66536, piece_count=243, source='Episode VI', release_year=2015,
         image_url='https://images.brickset.com/sets/images/66536-1.jpg?201509060932', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='UCS Slave I', set_number=75060, piece_count=1996, source='Episode V', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75060-1.jpg?201409070233', minifigures=['Boba Fett', 'Han Solo in Carbonite', 'Stormtrooper', 'Bespin Guard', 'Han Solo'], set_series='Star Wars').save()
    Lego(name='ARC-170 Starfighter Microfighter', set_number=75072, piece_count=95, source='Episode III', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75072-1.jpg?201410201106', minifigures=['Clone Pilot'], set_series='Star Wars').save()
    Lego(name='Vulture Droid Microfighter', set_number=75073, piece_count=77, source='Episode III', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75073-1.jpg?201410050944', minifigures=['Battle Droid Pilot'], set_series='Star Wars').save()
    Lego(name='Snowspeeder Microfighter', set_number=75074, piece_count=97, source='Episode V', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75074-1.jpg?201410050944', minifigures=['Rebel Snowspeeder Pilot'], set_series='Star Wars').save()
    Lego(name='AT-AT Microfighter', set_number=75075, piece_count=88, source='Episode V', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75075-1.jpg?201410050944', minifigures=['AT-AT Driver'], set_series='Star Wars').save()
    Lego(name='Republic Gunship Microfighter', set_number=75076, piece_count=105, source='Episode II', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75076-1.jpg?201410050944', minifigures=['Clone Pilot'], set_series='Star Wars').save()
    Lego(name='Homing Spider Droid Microfighter', set_number=75077, piece_count=102, source='Episode II', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75077-1.jpg?201410050944', minifigures=['Battle Droid'], set_series='Star Wars').save()
    Lego(name='Imperial Troop Transport', set_number=75078, piece_count=141, source='Rebels', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75078-1.jpg?201410050944', minifigures=['Stormtrooper (4x)'], set_series='Star Wars').save()
    Lego(name='Shadow Troopers', set_number=75079, piece_count=95, source='Expanded Universe', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75079-1.jpg?201410050944', minifigures=['Shadow Guard (2x)', 'Shadow Stormtrooper (2x)'], set_series='Star Wars').save()
    Lego(name='AAT', set_number=75080, piece_count=251, source='Episode I', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75080-1.jpg?201410050944', minifigures=['Jar Jar Binks', 'Battle Droid Pilot', 'Battle Droid'], set_series='Star Wars').save()
    Lego(name='T-16 Skyhopper', set_number=75081, piece_count=247, source='Episode IV', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75081-1.jpg?201410050944', minifigures=['T-16 Skyhopper Pilot', 'Tusken Raider'], set_series='Star Wars').save()
    Lego(name='TIE Advanced Prototype', set_number=75082, piece_count=355, source='Rebels', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75082-1.jpg?201410050944', minifigures=['The Inquisitor', 'TIE Fighter Pilot', 'Imperial Officer'], set_series='Star Wars').save()
    Lego(name='AT-DP', set_number=75083, piece_count=500, source='Rebels', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75083-1.jpg?201410050944', minifigures=['Agent Kallus', 'AT-DP Pilot (2x)', 'Stormtrooper'], set_series='Star Wars').save()
    Lego(name='Wookiee Gunship', set_number=75084, piece_count=570, source='Rebels', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75084-1.jpg?201407221154', minifigures=['Kanan Jarrus', 'Wookiee (2x)', 'Wullffwarro'], set_series='Star Wars').save()
    Lego(name='Hailfire Droid', set_number=75085, piece_count=163, source='Episode II', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75085-1.jpg?201410201106', minifigures=['Super Battle Droid (2x)', 'Clone Trooper Lieutenant'], set_series='Star Wars').save()
    Lego(name='Battle Droid Troop Carrier', set_number=75086, piece_count=565, source='Episode I', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75086-1.jpg?201410050944', minifigures=['Battle Droid (12x)', 'Battle Droid Pilot (2x)', 'Gungan Warrior'], set_series='Star Wars').save()
    Lego(name='Anakin\'s Custom Jedi Starfighter', set_number=75087, piece_count=370, source='Clone Wars', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75087-1.jpg?201410201106', minifigures=['Anakin Skywalker', 'Asajj Ventress', 'Astromech Droid'], set_series='Star Wars').save()

    Lego(name='', set_number=, piece_count=, source='', release_year=2015,
        image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='', release_year=2015,
        image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='', release_year=2015,
        image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='', release_year=2015,
        image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='', release_year=2015,
        image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='', release_year=2015,
        image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='', release_year=2015,
        image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='', release_year=2015,
        image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='', release_year=2015,
        image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='', release_year=2015,
        image_url='', minifigures=['', '', ''], set_series='Star Wars').save()

    # Lego(name='', set_number=, piece_count=, source='', release_year=2015,
    #     image_url='', minifigures=['', '', ''], set_series='Star Wars').save()


def fallow(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')
    Lego.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('legos', '0013_auto_20210119_2005'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
