# Generated by Django 3.1.4 on 2021-01-19 20:23

from django.db import migrations


def seed(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')

    Lego(name='A-Wing Starfighter', set_number=30272, piece_count=58, source='Episode VI', release_year=2015,
         image_url='https://images.brickset.com/sets/images/30272-1.jpg?201510151032', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='AT-DP', set_number=30274, piece_count=65, source='Rebels', release_year=2015,
         image_url='https://images.brickset.com/sets/images/30274-1.jpg?201510151032', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='TIE Advanced Prototype', set_number=30275, piece_count=47, source='Rebels', release_year=2015,
         image_url='https://images.brickset.com/sets/images/30275-1.jpg?201510151032', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='First Order Special Forces TIE Fighter', set_number=30276, piece_count=41, source='Episode VII', release_year=2015,
         image_url='https://images.brickset.com/sets/images/30276-1.jpg?201510151032', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Battle Pack 2 in 1', set_number=66535, piece_count=83, source='Episode III', release_year=2015,
         image_url='https://images.brickset.com/sets/images/66535-1.jpg?201511070947', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Battle Pack 2 in 1', set_number=66536, piece_count=243, source='Episode VI', release_year=2015,
         image_url='https://images.brickset.com/sets/images/66536-1.jpg?201509060932', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='UCS Slave I', set_number=75060, piece_count=1996, source='Episode V', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75060-1.jpg?201409070233', minifigures=['Boba Fett', 'Han Solo in Carbonite', 'Stormtrooper', 'Bespin Guard', 'Han Solo'], set_series='Star Wars').save()
    Lego(name='ARC-170 Starfighter Microfighter', set_number=75072, piece_count=95, source='Episode III', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75072-1.jpg?201410201106', minifigures=['Clone Pilot'], set_series='Star Wars').save()
    Lego(name='Vulture Droid Microfighter', set_number=75073, piece_count=77, source='Episode III', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75073-1.jpg?201410050944', minifigures=['Battle Droid Pilot'], set_series='Star Wars').save()
    Lego(name='Snowspeeder Microfighter', set_number=75074, piece_count=97, source='Episode V', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75074-1.jpg?201410050944', minifigures=['Rebel Snowspeeder Pilot'], set_series='Star Wars').save()
    Lego(name='AT-AT Microfighter', set_number=75075, piece_count=88, source='Episode V', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75075-1.jpg?201410050944', minifigures=['AT-AT Driver'], set_series='Star Wars').save()
    Lego(name='Republic Gunship Microfighter', set_number=75076, piece_count=105, source='Episode II', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75076-1.jpg?201410050944', minifigures=['Clone Pilot'], set_series='Star Wars').save()
    Lego(name='Homing Spider Droid Microfighter', set_number=75077, piece_count=102, source='Episode II', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75077-1.jpg?201410050944', minifigures=['Battle Droid'], set_series='Star Wars').save()
    Lego(name='Imperial Troop Transport', set_number=75078, piece_count=141, source='Rebels', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75078-1.jpg?201410050944', minifigures=['Stormtrooper (4x)'], set_series='Star Wars').save()
    Lego(name='Shadow Troopers', set_number=75079, piece_count=95, source='Expanded Universe', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75079-1.jpg?201410050944', minifigures=['Shadow Guard (2x)', 'Shadow Stormtrooper (2x)'], set_series='Star Wars').save()
    Lego(name='AAT', set_number=75080, piece_count=251, source='Episode I', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75080-1.jpg?201410050944', minifigures=['Jar Jar Binks', 'Battle Droid Pilot', 'Battle Droid'], set_series='Star Wars').save()
    Lego(name='T-16 Skyhopper', set_number=75081, piece_count=247, source='Episode IV', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75081-1.jpg?201410050944', minifigures=['T-16 Skyhopper Pilot', 'Tusken Raider'], set_series='Star Wars').save()
    Lego(name='TIE Advanced Prototype', set_number=75082, piece_count=355, source='Rebels', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75082-1.jpg?201410050944', minifigures=['The Inquisitor', 'TIE Fighter Pilot', 'Imperial Officer'], set_series='Star Wars').save()
    Lego(name='AT-DP', set_number=75083, piece_count=500, source='Rebels', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75083-1.jpg?201410050944', minifigures=['Agent Kallus', 'AT-DP Pilot (2x)', 'Stormtrooper'], set_series='Star Wars').save()
    Lego(name='Wookiee Gunship', set_number=75084, piece_count=570, source='Rebels', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75084-1.jpg?201407221154', minifigures=['Kanan Jarrus', 'Wookiee (2x)', 'Wullffwarro'], set_series='Star Wars').save()
    Lego(name='Hailfire Droid', set_number=75085, piece_count=163, source='Episode II', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75085-1.jpg?201410201106', minifigures=['Super Battle Droid (2x)', 'Clone Trooper Lieutenant'], set_series='Star Wars').save()
    Lego(name='Battle Droid Troop Carrier', set_number=75086, piece_count=565, source='Episode I', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75086-1.jpg?201410050944', minifigures=['Battle Droid (12x)', 'Battle Droid Pilot (2x)', 'Gungan Warrior'], set_series='Star Wars').save()
    Lego(name='Anakin\'s Custom Jedi Starfighter', set_number=75087, piece_count=370, source='Clone Wars', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75087-1.jpg?201410201106', minifigures=['Anakin Skywalker', 'Asajj Ventress', 'Astromech Droid'], set_series='Star Wars').save()

    Lego(name='Senate Commando Troopers', set_number=75088, piece_count=106, source='Clone Wars', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75088-1.jpg?201410080858', minifigures=['Senate Commando (3x)', 'Senate Commando Captain'], set_series='Star Wars').save()
    Lego(name='Geonosis Troopers', set_number=75089, piece_count=105, source='Clone Wars', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75089-1.jpg?201410050944', minifigures=['Geonosis Clone Trooper (2x)', 'Geonosis Airborne Trooper (2x)'], set_series='Star Wars').save()
    Lego(name='Ezra\'s Speeder Bike', set_number=75090, piece_count=253, source='Rebels', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75090-1.jpg?201410050944', minifigures=['Ezra Bridger', 'Sabine Wren', 'Stormtrooper'], set_series='Star Wars').save()
    Lego(name='Flash Speeder', set_number=75091, piece_count=312, source='Episode I', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75091-1.jpg?201505261128', minifigures=['Battle Droid (2x)', 'Captain Tarpals', 'Naboo Security Guard', 'Naboo Security Officer'], set_series='Star Wars').save()
    Lego(name='Naboo Starfighter', set_number=75092, piece_count=442, source='Episode I', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75092-1.jpg?201505261128', minifigures=['Anakin Skywalker', 'Obi-Wan Kenobi', 'Battle Droid Commander', 'Battle Droid (2x)', 'Droideka (2x)', 'Naboo Fighter Pilot', 'R2-D2'], set_series='Star Wars').save()
    Lego(name='Death Star Final Duel', set_number=75093, piece_count=724, source='Episode VI', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75093-1.jpg?201505261128', minifigures=['Darth Vader', 'Emperor Palpatine', 'Luke Skywalker (Jedi Master)', 'Royal Guard (2x)'], set_series='Star Wars').save()
    Lego(name='Imperial Shuttle Tydirium', set_number=75094, piece_count=937, source='Episode VI', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75094-1.jpg?201505261128', minifigures=['Chewbacca', 'Han Solo', 'Princess Leia', 'Endor Rebel Trooper (2x)'], set_series='Star Wars').save()
    Lego(name='UCS TIE Fighter', set_number=75095, piece_count=1685, source='Episode IV', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75095-1.jpg?201502141212', minifigures=['TIE Fighter Pilot'], set_series='Star Wars').save()
    Lego(name='Sith Infiltrator', set_number=75096, piece_count=662, source='Episode I', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75096-1.jpg?201507250125', minifigures=['Anakin Skywalker', 'Darth Maul', 'Qui-Gon Jinn', 'Watto', 'R2-D2', 'DRK-1 Probe Droid (3x)'], set_series='Star Wars').save()
    Lego(name='Star Wars Advent Calendar', set_number=75097, piece_count=292, source='Expanded Universe', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75097-1.jpg?201605181117', minifigures=['Assassin Droid', 'Ewok Warrior', 'Hoth Rebel Trooper', 'Imperial Probe Droid', 'Jawa', 'LIN Demolitionmech Droid', 'R2-D2 (Reindeer)', 'C-3PO (Santa)', 'Stormtrooper'], set_series='Star Wars').save()

    Lego(name='Rey\'s Speeder', set_number=75099, piece_count=193, source='Episode VII', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75099-1.jpg?201509061004', minifigures=['Rey', 'Unkar\'s Thug'], set_series='Star Wars').save()
    Lego(name='First Order Snowspeeder', set_number=75100, piece_count=444, source='Episode VII', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75100-1.jpg?201509061004', minifigures=['First Order Snowtrooper (2x)', 'First Order Snowtrooper Officer'], set_series='Star Wars').save()
    Lego(name='First Order Special Forces TIE Fighter', set_number=75101, piece_count=517, source='Episode VII', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75101-1.jpg?201509061004', minifigures=['First Order TIE Fighter Pilot', 'First Order Officer', 'First Order Crew Member'], set_series='Star Wars').save()
    Lego(name='Poe\'s X-wing Fighter', set_number=75102, piece_count=717, source='Episode VII', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75102-1.jpg?201509061004', minifigures=['BB-8', 'Poe Dameron', 'Resistance Ground Crew', 'Resistance X-Wing Pilot'], set_series='Star Wars').save()
    Lego(name='First Order Transporter', set_number=75103, piece_count=792, source='Episode VII', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75103-1.jpg?201509061004', minifigures=['Captain Phasma', 'First Order Flametrooper (2x)', 'First Order Stormtrooper (2x)', 'Resistance Soldier (2x)'], set_series='Star Wars').save()
    Lego(name='Kylo Ren\'s Command Shuttle', set_number=75104, piece_count=1005, source='Episode VII', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75104-1.jpg?201509061004', minifigures=['Kylo Ren', 'First Order Crew Member (2x)', 'First Order Officer', 'General Hux', 'First Order Stormtrooper Officer'], set_series='Star Wars').save()
    Lego(name='Millennium Falcon', set_number=75105, piece_count=1329, source='Episode VII', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75105-1.jpg?201509061004', minifigures=['BB-8', 'Chewbacca', 'Finn', 'Han Solo', 'Kanjiklub Gang Member', 'Rey', 'Tasu Leech'], set_series='Star Wars').save()
    Lego(name='Imperial Assault Carrier', set_number=75106, piece_count=1216, source='Rebels', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75106-1.jpg?201505261128', minifigures=['Agent Kallus', 'Imperial Astromech Droid', 'Imperial Officer', 'Sabine Wren', 'TIE Fighter Pilot (2x)'], set_series='Star Wars').save()
    Lego(name='Jango Fett', set_number=75107, piece_count=85, source='Episode II', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75107-1.jpg?201510140806', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Clone Commander Cody', set_number=75108, piece_count=82, source='Episode III', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75108-1.jpg?201510140806', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Obi-Wan Kenobi', set_number=75109, piece_count=83, source='Clone Wars', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75109-1.jpg?201510140806', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Luke Skywalker', set_number=75110, piece_count=83, source='Episode VI', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75110-1.jpg?201508271142', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Darth Vader', set_number=75111, piece_count=160, source='Episode IV', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75111-1.jpg?201508271142', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='General Grievous', set_number=75112, piece_count=186, source='Episode III', release_year=2015,
         image_url='https://images.brickset.com/sets/images/75112-1.jpg?201510140806', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Snowspeeder', set_number=911506, piece_count=19, source='Episode V', release_year=2015,
         image_url='https://images.brickset.com/sets/images/SW911506-1.jpg?201601051049', minifigures=['None'], set_series='Star Wars').save()

    Lego(name='Mini Slave I', set_number=911508, piece_count=20, source='Episode II', release_year=2015,
         image_url='https://images.brickset.com/sets/images/SW911508-1.jpg?201510240228', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Imperial Shooter', set_number=911509, piece_count=20, source='Rebels', release_year=2015,
         image_url='https://images.brickset.com/sets/images/SW911509-1.jpg?201902030901', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Micro Star Destroyer and TIE Fighter', set_number=911510, piece_count=21, source='Episode IV', release_year=2015,
         image_url='https://images.brickset.com/sets/images/SW911510-1.jpg?201510240229', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Jedi Weapon Stand', set_number=911511, piece_count=16, source='Expanded Universe', release_year=2015,
         image_url='https://images.brickset.com/sets/images/SW911511-1.jpg?201707180856', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Stormtrooper Sergeant', set_number=5002938, piece_count=5, source='Rebels', release_year=2015,
         image_url='https://images.brickset.com/sets/images/5002938-1.jpg?201605160804', minifigures=['Stormtrooper Sergeant'], set_series='Star Wars').save()
    Lego(name='The Phantom', set_number=5002939, piece_count=25, source='Rebels', release_year=2015,
         image_url='https://images.brickset.com/sets/images/5002939-1.jpg?201503130212', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Admiral Yularen', set_number=5002947, piece_count=4, source='Episode IV', release_year=2015,
         image_url='https://images.brickset.com/sets/images/5002947-1.jpg?201505040833', minifigures=['Admiral Yularen'], set_series='Star Wars').save()
    Lego(name='C-3PO', set_number=5002948, piece_count=3, source='Episode VII', release_year=2015,
         image_url='https://images.brickset.com/sets/images/5002948-1.jpg?201601050913', minifigures=['C-3PO'], set_series='Star Wars').save()

#     Lego(name='', set_number=, piece_count=, source='', release_year=2015,
#         image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    


def fallow(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')
    Lego.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('legos', '0013_auto_20210119_2005'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
