# Generated by Django 3.1.4 on 2021-01-22 22:33

from django.db import migrations


def seed(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')

    Lego(name='Sorting Hat', set_number=4701, piece_count=48, source='The Sorcerer\'s Stone', release_year=2001,
         image_url='https://images.brickset.com/sets/images/4701-1.jpg?200101131200', minifigures=['Harry Potter'], set_series='Harry Potter').save()
    Lego(name='The Final Challenge', set_number=4702, piece_count=60, source='The Sorcerer\'s Stone', release_year=2001,
         image_url='https://images.brickset.com/sets/images/4702-1.jpg?200101131200', minifigures=['Harry Potter', 'Professor Quirrell'], set_series='Harry Potter').save()
    Lego(name='The Room of the Winged Keys', set_number=4704, piece_count=175, source='The Sorcerer\'s Stone', release_year=2001,
         image_url='https://images.brickset.com/sets/images/4704-1.jpg?200101131200', minifigures=['Harry Potter', 'Ron Weasley', 'Chess Queen'], set_series='Harry Potter').save()
    Lego(name='Snape\'s Class', set_number=4705, piece_count=163, source='The Sorcerer\'s Stone', release_year=2001,
         image_url='https://images.brickset.com/sets/images/4705-1.jpg?200101131200', minifigures=['Professor Snape', 'Ron Weasley', 'Peeves'], set_series='Harry Potter').save()
    Lego(name='Forbidden Corridor', set_number=4706, piece_count=238, source='The Sorcerer\'s Stone', release_year=2001,
         image_url='https://images.brickset.com/sets/images/4706-1.jpg?200101131200', minifigures=['Harry Potter', 'Hermione Granger', 'Ron Weasley'], set_series='Harry Potter').save()
    Lego(name='Hagrid\'s Hut', set_number=4707, piece_count=299, source='The Sorcerer\'s Stone', release_year=2001,
         image_url='https://images.brickset.com/sets/images/4707-1.jpg?200101131200', minifigures=['Albus Dumbledore', 'Rubeus Hagrid'], set_series='Harry Potter').save()
    Lego(name='Hogwarts Express', set_number=4708, piece_count=410, source='The Sorcerer\'s Stone', release_year=2001,
         image_url='https://images.brickset.com/sets/images/4708-1.jpg?200101131200', minifigures=['Harry Potter', 'Hermione Granger', 'Ron Weasley'], set_series='Harry Potter').save()
    Lego(name='Hogwarts Castle', set_number=4709, piece_count=682, source='The Sorcerer\'s Stone', release_year=2001,
         image_url='https://images.brickset.com/sets/images/4709-1.jpg?200101131200', minifigures=['Harry Potter', 'Hermione Granger', 'Ron Weasley', 'Albus Dumbledore', 'Draco Malfoy', 'Gryffindor Knight Statue', 'Peeves', 'Professor Snape', 'Rubeus Hagrid'], set_series='Harry Potter').save()
    Lego(name='Hogwarts Classrooms', set_number=4721, piece_count=73, source='The Sorcerer\'s Stone', release_year=2001,
         image_url='https://images.brickset.com/sets/images/4721-1.jpg?200106171200', minifigures=['Harry Potter'], set_series='Harry Potter').save()
    Lego(name='Gryffindor House', set_number=4722, piece_count=68, source='The Sorcerer\'s Stone', release_year=2001,
         image_url='https://images.brickset.com/sets/images/4722-1.jpg?200106171200', minifigures=['Ron Weasley'], set_series='Harry Potter').save()
    Lego(name='Diagon Alley Shops', set_number=4723, piece_count=80, source='The Sorcerer\'s Stone', release_year=2001,
         image_url='https://images.brickset.com/sets/images/4723-1.jpg?200106171200', minifigures=['Hermione Granger'], set_series='Harry Potter').save()

    Lego(name='Flying Lesson', set_number=4711, piece_count=23, source='The Sorcerer\'s Stone', release_year=2002,
         image_url='https://images.brickset.com/sets/images/4711-1.jpg?200110301200', minifigures=['Harry Potter', 'Draco Malfoy'], set_series='Harry Potter').save()
    Lego(name='Troll on the Loose', set_number=4712, piece_count=71, source='The Sorcerer\'s Stone', release_year=2002,
         image_url='https://images.brickset.com/sets/images/4712-1.jpg?200110301200', minifigures=['Harry Potter', 'Troll'], set_series='Harry Potter').save()
    Lego(name='Gringott\'s Bank', set_number=4714, piece_count=250, source='The Sorcerer\'s Stone', release_year=2002,
         image_url='https://images.brickset.com/sets/images/4714-1.jpg?200110301200', minifigures=['Harry Potter', 'Rubeus Hagrid', 'Goblin (2x)'], set_series='Harry Potter').save()
    Lego(name='Quidditch Practice', set_number=4726, piece_count=128, source='Chamber of Secrets', release_year=2002,
         image_url='https://images.brickset.com/sets/images/4726-1.jpg?200205100606', minifigures=['Madame Hooch', 'Draco Malfoy', 'Harry Potter'], set_series='Harry Potter').save()
    Lego(name='Aragog in the Dark Forest', set_number=4727, piece_count=178, source='Chamber of Secrets', release_year=2002,
         image_url='https://images.brickset.com/sets/images/4727-1.jpg?200205100607', minifigures=['Harry Potter', 'Ron Weasley'], set_series='Harry Potter').save()
    Lego(name='Escape from Privet Drive', set_number=4728, piece_count=278, source='Chamber of Secrets', release_year=2002,
         image_url='https://images.brickset.com/sets/images/4728-1.jpg?200205100608', minifigures=['Harry Potter', 'Ron Weasley', 'Vernon Dursley'], set_series='Harry Potter').save()
    Lego(name='Dumbledore\'s Office', set_number=4729, piece_count=446, source='Chamber of Secrets', release_year=2002,
         image_url='https://images.brickset.com/sets/images/4729-1.jpg?200205100610', minifigures=['Harry Potter', 'Albus Dumbledore', 'Minerva McGonagall'], set_series='Harry Potter').save()
    Lego(name='The Chamber of Secrets', set_number=4730, piece_count=591, source='Chamber of Secrets', release_year=2002,
         image_url='https://images.brickset.com/sets/images/4730-1.jpg?200205100611', minifigures=['Harry Potter', 'Ron Weasley', 'Ginny Weasley', 'Gilderoy Lockhart', 'Tom Riddle'], set_series='Harry Potter').save()
    Lego(name='Dobby\'s Release', set_number=4731, piece_count=70, source='Chamber of Secrets', release_year=2002,
         image_url='https://images.brickset.com/sets/images/4731-1.jpg?200205100612', minifigures=['Dobby', 'Lucius Malfoy'], set_series='Harry Potter').save()
    Lego(name='The Dueling Club', set_number=4733, piece_count=129, source='Chamber of Secrets', release_year=2002,
         image_url='https://images.brickset.com/sets/images/4733-1.jpg?200205100613', minifigures=['Harry Potter', 'Draco Malfoy', 'Severus Snape', 'Gilderoy Lockhart'], set_series='Harry Potter').save()
    Lego(name='Slytherin', set_number=4735, piece_count=90, source='Chamber of Secrets', release_year=2002,
         image_url='https://images.brickset.com/sets/images/4735-1.jpg?200205100614', minifigures=['Draco Malfoy', 'Harry/Goyle', 'Ron/Crabbe'], set_series='Harry Potter').save()


    # Lego(name='', set_number=, piece_count=, source='', release_year=2002,
    #     image_url='', minifigures=['', '', ''], set_series='Harry Potter').save()

def fallow(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')
    Lego.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('legos', '0014_auto_20210119_2023'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
