# Generated by Django 3.1.4 on 2021-01-27 20:06

from django.db import migrations

def seed(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')

    Lego(name='Quality Quidditch Supplies', set_number=4719, piece_count=120, source='Chamber of Secrets', release_year=2003,
         image_url='https://images.brickset.com/sets/images/4719-1.jpg?200212311022', minifigures=['Draco Malfoy'], set_series='Harry Potter').save()
    Lego(name='Knockturn Alley', set_number=4720, piece_count=209, source='Chamber of Secrets', release_year=2003,
         image_url='https://images.brickset.com/sets/images/4720-1.jpg?200212311024', minifigures=['Harry Potter', 'Lucius Malfoy'], set_series='Harry Potter').save()

    Lego(name='Mini Harry Potter Knight Bus', set_number=4695, piece_count=58, source='Prisoner of Azkaban', release_year=2004,
         image_url='https://images.brickset.com/sets/images/4695-1.jpg?200403130527', minifigures=['None'], set_series='Harry Potter').save()
    Lego(name='Draco\'s Encounter with Buckbeak', set_number=4750, piece_count=36, source='Prisoner of Azkaban', release_year=2004,
         image_url='https://images.brickset.com/sets/images/4750-1.jpg?200401100736', minifigures=['Draco Malfoy'], set_series='Harry Potter').save()
    Lego(name='Harry and the Marauder\'s Map', set_number=4751, piece_count=109, source='Prisoner of Azkaban', release_year=2004,
         image_url='https://images.brickset.com/sets/images/4751-1.jpg?200401100739', minifigures=['Harry Potter', 'Severus Snape', 'Marauder\'s Map Statue'], set_series='Harry Potter').save()
    Lego(name='Professor Lupin\'s Classroom', set_number=4752, piece_count=156, source='Prisoner of Azkaban', release_year=2004,
         image_url='https://images.brickset.com/sets/images/4752-1.jpg?200401100740', minifigures=['Remus Lupin', 'Neville Longbottom', 'Snape (Boggart)'], set_series='Harry Potter').save()
    Lego(name='Sirius Black\'s Escape', set_number=4753, piece_count=188, source='Prisoner of Azkaban', release_year=2004,
         image_url='https://images.brickset.com/sets/images/4753-1.jpg?200401100741', minifigures=['Dementor', 'Harry Potter', 'Sirius Black'], set_series='Harry Potter').save()
    Lego(name='Hagrid\'s Hut', set_number=4754, piece_count=302, source='Prisoner of Azkaban', release_year=2004,
         image_url='https://images.brickset.com/sets/images/4754-1.jpg?200401100743', minifigures=['Hermione Granger', 'Rubeus Hagrid'], set_series='Harry Potter').save()
    Lego(name='Knight Bus', set_number=4755, piece_count=243, source='Prisoner of Azkaban', release_year=2004,
         image_url='https://images.brickset.com/sets/images/4755-1.jpg?200401100744', minifigures=['Harry Potter', 'Stan Shunpike'], set_series='Harry Potter').save()
    Lego(name='Shrieking Shack', set_number=4756, piece_count=444, source='Prisoner of Azkaban', release_year=2004,
         image_url='https://images.brickset.com/sets/images/4756-1.jpg?200401100745', minifigures=['Harry Potter', 'Peter Pettigrew', 'Remus Lupin (Werewolf)', 'Sirius Black'], set_series='Harry Potter').save()
    Lego(name='Hogwarts Castle', set_number=4757, piece_count=944, source='Prisoner of Azkaban', release_year=2004,
         image_url='https://images.brickset.com/sets/images/4757-1.jpg?200401100746', minifigures=['Albus Dumbledore', 'Harry Potter', 'Ron Weasley', 'Hermione Granger', 'Dementor (2x)', 'Draco Malfoy', 'Sybill Trelawney', 'Skeleton'], set_series='Harry Potter').save()
    Lego(name='Hogwarts Express', set_number=4758, piece_count=389, source='Prisoner of Azkaban', release_year=2004,
         image_url='https://images.brickset.com/sets/images/4758-1.jpg?200401100747', minifigures=['Harry Potter', 'Ron Weasley', 'Remus Lupin', 'Dementor'], set_series='Harry Potter').save()
    Lego(name='Motorized Hogwarts Express', set_number=10132, piece_count=708, source='Prisoner of Azkaban', release_year=2004,
         image_url='https://images.brickset.com/sets/images/10132-1.jpg?200402040157', minifigures=['Harry Potter', 'Ron Weasley', 'Remus Lupin', 'Dementor'], set_series='Harry Potter').save()

    Lego(name='Rescue from the Merpeople', set_number=4762, piece_count=175, source='Goblet of Fire', release_year=2005,
         image_url='https://images.brickset.com/sets/images/4762-1.jpg?200508310231', minifigures=['Harry Potter', 'Hermione Granger', 'Ron Weasley', 'Merman', 'Viktor Krum (Shark Head)'], set_series='Harry Potter').save()
    Lego(name='Graveyard Duel', set_number=4766, piece_count=548, source='Goblet of Fire', release_year=2005,
         image_url='https://images.brickset.com/sets/images/4766-1.jpg?200508310231', minifigures=['Death Eater', 'Harry Potter', 'Skeleton (4x)', 'Voldemort', 'Peter Pettigrew'], set_series='Harry Potter').save()
    Lego(name='Harry and the Hungarian Horntail', set_number=4767, piece_count=265, source='Goblet of Fire', release_year=2005,
         image_url='https://images.brickset.com/sets/images/4767-1.jpg?200508310232', minifigures=['Albus Dumbledore', 'Mad-Eye Moody', 'Harry Potter'], set_series='Harry Potter').save()
    Lego(name='The Durmstrang Ship', set_number=4768, piece_count=550, source='Goblet of Fire', release_year=2005,
         image_url='https://images.brickset.com/sets/images/4768-1.jpg?200508310233', minifigures=['Igor Karkaroff', 'Viktor Krum'], set_series='Harry Potter').save()
    Lego(name='The Durmstrang Ship with Bonus Minifigures', set_number=4768, piece_count=566, source='Goblet of Fire', release_year=2005,
         image_url='https://images.brickset.com/sets/images/4768-2.jpg?201112120103', minifigures=['Igor Karkaroff', 'Viktor Krum', 'Albus Dumbledore', 'Harry Potter', 'Hermione Granger', 'Ron Weasley'], set_series='Harry Potter').save()

    Lego(name='Hogwarts Castle', set_number=5378, piece_count=943, source='Order of the Phoenix', release_year=2007,
         image_url='https://images.brickset.com/sets/images/5378-1.jpg?200704270313', minifigures=['Albus Dumbledore', 'Death Eater', 'Draco Malfoy', 'Harry Potter', 'Hermione Granger', 'Ron Weasley', 'Dolores Umbridge', 'Severus Snape', 'Rubeus Hagrid'], set_series='Harry Potter').save()

    Lego(name='Freeing Dobby', set_number=4736, piece_count=73, source='Chamber of Secrets', release_year=2010,
         image_url='https://images.brickset.com/sets/images/4736-1.jpg?201009010137', minifigures=['Dobby', 'Harry Potter', 'Lucius Malfoy'], set_series='Harry Potter').save()
    Lego(name='Quidditch Match', set_number=4737, piece_count=153, source='Chamber of Secrets', release_year=2010,
         image_url='https://images.brickset.com/sets/images/4737-1.jpg?201010040320', minifigures=['Madame Hooch', 'Harry Potter', 'Oliver Wood', 'Draco Malfoy', 'Marcus Flint'], set_series='Harry Potter').save()
    Lego(name='Hagrid\'s Hut', set_number=4738, piece_count=442, source='Chamber of Secrets', release_year=2010,
         image_url='https://images.brickset.com/sets/images/4738-1.jpg?201009301135', minifigures=['Rubeus Hagrid', 'Harry Potter', 'Hermione Granger', 'Ron Weasley'], set_series='Harry Potter').save()
    Lego(name='The Burrow', set_number=4840, piece_count=568, source='Half-Blood Prince', release_year=2010,
         image_url='https://images.brickset.com/sets/images/4840-1.jpg?201009010138', minifigures=['Arthur Weasley', 'Molly Weasley', 'Ginny Weasley', 'Bellatrix Lestrange', 'Fenrir Greyback', 'Harry Potter'], set_series='Harry Potter').save()
    Lego(name='Hogwarts Express', set_number=4841, piece_count=646, source='General', release_year=2010,
         image_url='https://images.brickset.com/sets/images/4841-1.jpg?201009301136', minifigures=['Harry Potter', 'Luna Lovergood', 'Ginny Weasley', 'Ron Weasley', 'Draco Malfoy'], set_series='Harry Potter').save()
    Lego(name='Hogwarts Castle', set_number=4842, piece_count=1290, source='General', release_year=2010,
         image_url='https://images.brickset.com/sets/images/4842-1.jpg?201009010137', minifigures=['Albus Dumbledore', 'Argus Filch', 'Dementor (2x)', 'Gryffindor Knight Statue', 'Harry Potter', 'Hermione Granger', 'Filius Flitwick', 'Minerva McGonagall', 'Severus Snape', 'Voldemort'], set_series='Harry Potter').save()

    Lego(name='The Forbidden Forest', set_number=4865, piece_count=64, source='Deathly Hallows', release_year=2011,
         image_url='https://images.brickset.com/sets/images/4865-1.jpg?201103240404', minifigures=['Rubeus Hagrid', 'Harry Potter', 'Voldemort', 'Narcissa Malfoy'], set_series='Harry Potter').save()
    Lego(name='The Knight Bus', set_number=4866, piece_count=257, source='Prisoner of Azkaban', release_year=2011,
         image_url='https://images.brickset.com/sets/images/4866-1.jpg?201103240404', minifigures=['Harry Potter', 'Ernie Prang', 'Stan Shunpike'], set_series='Harry Potter').save()
    Lego(name='Hogwarts', set_number=4867, piece_count=466, source='Deathly Hallows', release_year=2011,
         image_url='https://images.brickset.com/sets/images/4867-1.jpg?201103240404', minifigures=['Dementor', 'Gregory Goyle', 'Harry Potter', 'Lucius Malfoy', 'Neville Longbottom', 'Pomona Sprout', 'Remus Lupin'], set_series='Harry Potter').save()
    Lego(name='Diagon Alley', set_number=10217, piece_count=2025, source='General', release_year=2011,
         image_url='https://images.brickset.com/sets/images/10217-1.jpg?201012240436', minifigures=['Fenrir Greyback', 'Fred Weasley', 'George Weasley', 'Garrick Ollivander', 'Goblin (2x)', 'Harry Potter', 'Hermione Granger', 'Ron Weasley', 'Lucius Malfoy', 'Rubeus Hagrid', 'Skeleton'], set_series='Harry Potter').save()
    Lego(name='Trolley', set_number=30110, piece_count=22, source='General', release_year=2011,
         image_url='https://images.brickset.com/sets/images/30110-1.jpg?201104020824', minifigures=['Harry Potter'], set_series='Harry Potter').save()
    Lego(name='The Lab', set_number=30111, piece_count=34, source='General', release_year=2011,
         image_url='https://images.brickset.com/sets/images/30111-1.jpg?201104020824', minifigures=['Harry Potter'], set_series='Harry Potter').save()
    Lego(name='Mini Hogwarts Express', set_number=40028, piece_count=64, source='General', release_year=2011,
         image_url='https://images.brickset.com/sets/images/40028-1.jpg?201605160905', minifigures=['None'], set_series='Harry Potter').save()

    Lego(name='Harry\'s Journey to Hogwarts', set_number=30407, piece_count=40, source='The Sorcerer\'s Stone', release_year=2018,
         image_url='https://images.brickset.com/sets/images/30407-1.jpg?201810030355', minifigures=['Harry Potter'], set_series='Harry Potter').save()
    Lego(name='Diagon Alley', set_number=40289, piece_count=374, source='General', release_year=2018,
         image_url='https://images.brickset.com/sets/images/40289-1.jpg?201810250747', minifigures=['Garrick Ollivander'], set_series='Harry Potter').save()
    Lego(name='Hogwarts Castle', set_number=71043, piece_count=6020, source='General', release_year=2018,
         image_url='https://images.brickset.com/sets/images/71043-1.jpg?201807250319', minifigures=['Godric Gryffindor', 'Salazar Slytherin', 'Helga Hufflepuff', 'Rowena Ravenclaw'], set_series='Harry Potter').save()
    Lego(name='Aragog\'s Lair', set_number=75950, piece_count=157, source='Chamber of Secrets', release_year=2018,
         image_url='https://images.brickset.com/sets/images/75950-1.jpg?201806220833', minifigures=['Harry Potter', 'Ron Weasley'], set_series='Harry Potter').save()
    Lego(name='Grindelwald\'s Escape', set_number=75951, piece_count=132, source='Fantastic Beasts', release_year=2018,
         image_url='https://images.brickset.com/sets/images/75951-1.jpg?201805260756', minifigures=['Gellert Grindelwald', 'Seraphina Picquery'], set_series='Harry Potter').save()
    Lego(name='Newt\'s Case of Magical Creatures', set_number=75952, piece_count=694, source='Fantastic Beasts', release_year=2018,
         image_url='https://images.brickset.com/sets/images/75952-1.jpg?201807130816', minifigures=['Jacob Kowalski', 'Newt Scamander', 'Queenie Goldstein', 'Tina Goldstein'], set_series='Harry Potter').save()
    Lego(name='Hogwarts Whomping Willow', set_number=75953, piece_count=753, source='Chamber of Secrets', release_year=2018,
         image_url='https://images.brickset.com/sets/images/75953-1.jpg?201805260756', minifigures=['Argus Filch', 'Harry Potter', 'Ron Weasley', 'Hermione Granger', 'Severus Snape', 'Seamus Finnigan', ''], set_series='Harry Potter').save()
    Lego(name='Hogwarts Great Hall', set_number=75954, piece_count=878, source='The Sorcerer\'s Stone', release_year=2018,
         image_url='https://images.brickset.com/sets/images/75954-1.jpg?201805260756', minifigures=['Albus Dumbledore', 'Draco Malfoy', 'Harry Potter', 'Hermione Granger', 'Ron Weasley', 'Nearly Headless Nick', 'Minerva McGonagall', 'Quirinus Quirrell', 'Rubeus Hagrid', 'Susan Bones'], set_series='Harry Potter').save()
    Lego(name='Hogwarts Express', set_number=75955, piece_count=801, source='Prisoner of Azkaban', release_year=2018,
         image_url='https://images.brickset.com/sets/images/75955-1.jpg?201807101202', minifigures=['Dementor', 'Harry Potter', 'Hermione Granger',' Ron Weasley', 'Remus Lupin', 'Trolley Witch'], set_series='Harry Potter').save()
    Lego(name='Quidditch Match', set_number=75956, piece_count=500, source='The Sorcerer\'s Stone', release_year=2018,
         image_url='https://images.brickset.com/sets/images/75956-1.jpg?201805260756', minifigures=['Harry Potter', 'Hermione Granger', 'Lucian Bole', 'Marcus Flint', 'Oliver Wood', 'Severus Snape'], set_series='Harry Potter').save()
    Lego(name='Harry Potter Minifigure Collection', set_number=5005254, piece_count=25, source='General', release_year=2018,
         image_url='https://images.brickset.com/sets/images/5005254-1.jpg?201808220510', minifigures=['Madame Hooch', 'Horace Slughorn', 'Dolores Umbridge', 'Severus Snape (Boggart)'], set_series='Harry Potter').save()

    Lego(name='Expecto Patronum', set_number=75945, piece_count=121, source='Prisoner of Azkaban', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75945-1.jpg?201905140825', minifigures=['Dementor (2x)', 'Sirius Black', 'Harry Potter'], set_series='Harry Potter').save()
    Lego(name='Hungarian Horntail Triwizard Challenge', set_number=75946, piece_count=265, source='Goblet of Fire', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75946-1.jpg?201905140825', minifigures=['Harry Potter', 'Viktor Krum', 'Cedric Diggory', 'Fleur Delacour'], set_series='Harry Potter').save()
    Lego(name='Hagrid\'s Hut: Buckbeak\'s Rescue', set_number=75947, piece_count=496, source='Prisoner of Azkaban', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75947-1.jpg?201905140825', minifigures=['Executioner', 'Rubeus Hagrid', 'Harry Potter', 'Hermione Granger', 'Cornelius Fudge', 'Ron Weasley'], set_series='Harry Potter').save()
    Lego(name='Hogwarts Clock Tower', set_number=75948, piece_count=922, source='Goblet of Fire', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75948-1.jpg?201905140825', minifigures=['Albus Dumbledore', 'Cedric Diggory', 'Fleur Delacour', 'Harry Potter', 'Hermione Granger', 'Madame Maxime', 'Ron Weasley', 'Viktor Krum'], set_series='Harry Potter').save()
    Lego(name='The Knight Bus', set_number=75957, piece_count=403, source='Prisoner of Azkaban', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75957-1.jpg?201905140825', minifigures=['Ernie Prang', 'Stan Shunpike', 'Harry Potter'], set_series='Harry Potter').save()
    Lego(name='Beauxbaton\'s Carriage: Arrival at Hogwarts', set_number=75958, piece_count=430, source='Goblet of Fire', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75958-1.jpg?201907130955', minifigures=['Rubeus Hagrid', 'Madame Maxime', 'Fleur Delacour', 'Gabrielle Delacour'], set_series='Harry Potter').save()
    Lego(name='Harry Potter Advent Calendar', set_number=75964, piece_count=305, source='General', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75964-1.jpg?201911251110', minifigures=['Albus Dumbledore', 'Harry Potter', 'Hermione Granger', 'Ron Weasley', 'Hogwarts Architect Statue', 'Filius Flitwick', 'Minerva McGonagall', 'Snow Wizard'], set_series='Harry Potter').save()
    Lego(name='The Rise of Voldemort', set_number=75965, piece_count=184, source='Goblet of Fire', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75965-1.jpg?201907130955', minifigures=['Voldemort', 'Harry Potter', 'Baby Voldemort', 'Death Eater', 'Peter Pettigrew', 'Tom Riddle Grave Statue'], set_series='Harry Potter').save()

    Lego(name='', set_number=, piece_count=, source='', release_year=2020,
        image_url='', minifigures=['', '', ''], set_series='Harry Potter').save()

def fallow(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')
    Lego.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('legos', '0015_auto_20210122_2233'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
