# Generated by Django 3.1.4 on 2021-02-16 18:13

from django.db import migrations


def seed(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')

    Lego(name='First Order Star Destroyer', set_number=30277, piece_count=56, source='Episode VII', release_year=2016,
         image_url='https://images.brickset.com/sets/images/30277-1.jpg?201601031117', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Poe\'s X-Wing Fighter', set_number=30278, piece_count=64, source='Episode VII', release_year=2016,
         image_url='https://img.bricklink.com/ItemImage/SL/30278-1.png', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Kylo Ren\'s Command Shuttle', set_number=30279, piece_count=43, source='Episode VII', release_year=2016,
         image_url='https://images.brickset.com/sets/images/30279-1.jpg?201601181009', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='First Order Stormtrooper', set_number=30602, piece_count=7, source='Episode VII', release_year=2016,
         image_url='https://images.brickset.com/sets/images/30602-1.jpg?201603230839', minifigures=['First Order Stormtrooper'], set_series='Star Wars').save()
    Lego(name='Finn (FN-2187)', set_number=30605, piece_count=5, source='Episode VII', release_year=2016,
         image_url='https://images.brickset.com/sets/images/30605-1.jpg?201512160948', minifigures=['Finn (FN-2187)'], set_series='Star Wars').save()
    Lego(name='Assault on Hoth', set_number=75098, piece_count=2144, source='Episode V', release_year=2016,
         image_url='https://images.brickset.com/sets/images/75098-1.jpg?201605161135', minifigures=['R3-A2', 'Han Solo (Hoth)', 'Hoth Rebel Trooper (5x)', 'K-3PO', 'Luke Skywalker (Hoth)', 'Rebel Officer', 'Snowtrooper (2x)', 'Toryn Farr', 'Wedge Antilles', 'Wes Janson'], set_series='Star Wars').save()
    Lego(name='Rey', set_number=75113, piece_count=84, source='Episode VII', release_year=2016,
         image_url='https://images.brickset.com/sets/images/75113-1.jpg?201511230710', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='First Order Stormtrooper', set_number=75114, piece_count=81, source='Episode VII', release_year=2016,
         image_url='https://images.brickset.com/sets/images/75114-1.jpg?201511230710', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Poe Dameron', set_number=75115, piece_count=102, source='Episode VII', release_year=2016,
         image_url='https://images.brickset.com/sets/images/75115-1.jpg?201511230710', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Finn', set_number=75116, piece_count=98, source='Episode VII', release_year=2016,
         image_url='https://images.brickset.com/sets/images/75116-1.jpg?201511230710', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Kylo Ren', set_number=75117, piece_count=86, source='Episode VII', release_year=2016,
         image_url='https://images.brickset.com/sets/images/75117-1.jpg?201511230710', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Captain Phasma', set_number=75118, piece_count=82, source='Episode VII', release_year=2016,
         image_url='https://images.brickset.com/sets/images/75118-1.jpg?201511230710', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Sergeant Jyn Erso', set_number=75119, piece_count=104, source='Rogue One', release_year=2016,
         image_url='https://images.brickset.com/sets/images/75119-1.jpg?201609201033', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='K-2SO', set_number=75120, piece_count=169, source='Rogue One', release_year=2016,
         image_url='https://images.brickset.com/sets/images/75120-1.jpg?201609201033', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Imperial Death Trooper', set_number=75121, piece_count=106, source='Rogue One', release_year=2016,
         image_url='https://images.brickset.com/sets/images/75121-1.jpg?201609201033', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Resistance X-Wing Fighter, Microfighter', set_number=75125, piece_count=87, source='Episode VII', release_year=2016,
         image_url='https://images.brickset.com/sets/images/75125-1.jpg?201601050913', minifigures=['Resistance X-Wing Pilot'], set_series='Star Wars').save()
    Lego(name='First Order Snowspeeder Microfighter', set_number=75126, piece_count=91, source='Episode VII', release_year=2016,
         image_url='https://images.brickset.com/sets/images/75126-1.jpg?201601050913', minifigures=['First Order Snowtrooper'], set_series='Star Wars').save()
    Lego(name='The Ghost Microfighter', set_number=75127, piece_count=104, source='Rebels', release_year=2016,
         image_url='https://images.brickset.com/sets/images/75127-1.jpg?201601050913', minifigures=['Hera Syndulla'], set_series='Star Wars').save()
    Lego(name='TIE Advanced Prototype Microfighter', set_number=75128, piece_count=93, source='Rebels', release_year=2016,
         image_url='https://images.brickset.com/sets/images/75128-1.jpg?201601050913', minifigures=['TIE Fighter Pilot'], set_series='Star Wars').save()
    Lego(name='Wookiee Gunship Microfighter', set_number=75129, piece_count=84, source='Rebels', release_year=2016,
         image_url='https://images.brickset.com/sets/images/75129-1.jpg?201601050913', minifigures=['Wookiee'], set_series='Star Wars').save()
    Lego(name='AT-DP Microfighter', set_number=75130, piece_count=76, source='Rebels', release_year=2016,
         image_url='https://images.brickset.com/sets/images/75130-1.jpg?201601050913', minifigures=['AT-DP Pilot'], set_series='Star Wars').save()
    Lego(name='Resistance Trooper Battle Pack', set_number=75131, piece_count=112, source='Episode VII', release_year=2016,
         image_url='https://images.brickset.com/sets/images/75131-1.jpg?201601050913', minifigures=['Resistance Officer', 'Resistance Trooper (3x)'], set_series='Star Wars').save()

    Lego(name='', set_number=, piece_count=, source='', release_year=2016,
        image_url='', minifigures=['', '', ''], set_series='Star Wars').save()

    # Lego(name='', set_number=, piece_count=, source='', release_year=2016,
    #     image_url='', minifigures=['', '', ''], set_series='Star Wars').save()

def fallow(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')
    Lego.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('legos', '0016_auto_20210127_2006'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
