# Generated by Django 3.1.4 on 2021-02-17 19:24

from django.db import migrations


def seed(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')

    Lego(name='U-Wing Fighter', set_number=30496, piece_count=55, source='Rogue One', release_year=2017,
         image_url='https://images.brickset.com/sets/images/30496-1.jpg?201701030431', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='First Order Heavy Assault Walker', set_number=30497, piece_count=54, source='Episode VIII', release_year=2017,
         image_url='https://images.brickset.com/sets/images/30497-1.jpg?201709260948', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='R2-D2', set_number=30611, piece_count=70, source='Episode IV', release_year=2017,
         image_url='https://images.brickset.com/sets/images/30611-1.jpg?201703220726', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Scarif Stormtrooper', set_number=40176, piece_count=25, source='Rogue One', release_year=2017,
         image_url='https://images.brickset.com/sets/images/40176-1.jpg?201709041134', minifigures=['Scarif Stormtrooper'], set_series='Star Wars').save()
    Lego(name='R3-M2', set_number=40268, piece_count=21, source='Rogue One', release_year=2017,
         image_url='https://images.brickset.com/sets/images/40268-1.jpg?201703290940', minifigures=['R3-M2'], set_series='Star Wars').save()
    Lego(name='UCS Snowspeeder', set_number=75144, piece_count=1703, source='Episode V', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75144-1.jpg?201703220726', minifigures=['Zev Senesca', 'Will Scotian'], set_series='Star Wars').save()
    Lego(name='U-wing Microfighter', set_number=75160, piece_count=109, source='Rogue One', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75160-1.jpg?201612020919', minifigures=['Rebel U-Wing Pilot'], set_series='Star Wars').save()
    Lego(name='TIE Striker Microfighter', set_number=75161, piece_count=88, source='Rogue One', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75161-1.jpg?201612020919', minifigures=['TIE Striker Pilot'], set_series='Star Wars').save()
    Lego(name='Y-wing Microfighter', set_number=75162, piece_count=90, source='Rogue One', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75162-1.jpg?201612020919', minifigures=['Rebel Y-Wing Pilot'], set_series='Star Wars').save()
    Lego(name='Krennic\'s Imperial Shuttle Microfighter', set_number=75163, piece_count=78, source='Rogue One', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75163-1.jpg?201612020919', minifigures=['Imperial Shuttle Pilot'], set_series='Star Wars').save()
    Lego(name='Rebel Trooper Battle Pack', set_number=75164, piece_count=120, source='Rogue One', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75164-1.jpg?201612020919', minifigures=['Rebel Trooper (4x)'], set_series='Star Wars').save()
    Lego(name='Imperial Trooper Battle Pack', set_number=75165, piece_count=112, source='Rogue One', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75165-1.jpg?201612020919', minifigures=['Imperial Death Trooper (2x)', 'Stormtrooper (2x)'], set_series='Star Wars').save()
    Lego(name='First Order Transport Speeder Battle Pack', set_number=75166, piece_count=117, source='Episode VII', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75166-1.jpg?201707191128', minifigures=['First Order Flametrooper', 'First Order Officer', 'First Order Stormtrooper (2x)'], set_series='Star Wars').save()
    Lego(name='Bounty Hunter Speeder Bike Battle Pack', set_number=75167, piece_count=125, source='Expanded Universe', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75167-1.jpg?201705210933', minifigures=['4-LOM', 'Bossk', 'Dengar', 'IG-88'], set_series='Star Wars').save()
    Lego(name='Yoda\'s Jedi Starfighter', set_number=75168, piece_count=262, source='Clone Wars', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75168-1.jpg?201611300919', minifigures=['Yoda', 'R2-D2'], set_series='Star Wars').save()
    Lego(name='Duel on Naboo', set_number=75169, piece_count=208, source='Episode I', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75169-1.jpg?201611300919', minifigures=['Qui-Gon Jinn', 'Obi-Wan Kenobi', 'Darth Maul'], set_series='Star Wars').save()
    Lego(name='The Phantom', set_number=75170, piece_count=269, source='Rebels', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75170-1.jpg?201611300919', minifigures=['Chopper', 'Kanan Jarrus', 'Admiral Thrawn'], set_series='Star Wars').save()
    Lego(name='Battle on Scarif', set_number=75171, piece_count=419, source='Rogue One', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75171-1.jpg?201612020919', minifigures=['Cassian Andor', 'Jyn Erso', 'Scarif Stormtrooper (2x)'], set_series='Star Wars').save()
    Lego(name='Y-wing Starfighter', set_number=75172, piece_count=691, source='Rogue One', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75172-1.jpg?201612020919', minifigures=['Admiral Raddus', 'R3-S1', 'Moroff', 'Rebel Pilot', 'Stormtrooper'], set_series='Star Wars').save()
    Lego(name='Luke\'s Landspeeder', set_number=75173, piece_count=149, source='Episode IV', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75173-1.jpg?201611300919', minifigures=['C-3PO', 'Ben Kenobi', 'Luke Skywalker', 'Tusken Raider'], set_series='Star Wars').save()
    Lego(name='Desert Skiff Escape', set_number=75174, piece_count=277, source='Episode VI', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75174-1.jpg?201611300919', minifigures=['Boba Fett', 'Han Solo', 'Chewbacca', 'Skiff Guard'], set_series='Star Wars').save()
    Lego(name='A-wing Starfighter', set_number=75175, piece_count=358, source='Episode VI', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75175-1.jpg?201611300919', minifigures=['Lando Calrissian', 'Rebel Ground Crew', 'Rebel A-Wing Pilot'], set_series='Star Wars').save()
    Lego(name='Resistance Transport Pod', set_number=75176, piece_count=294, source='Episode VIII', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75176-1.jpg?201709041134', minifigures=['Finn', 'Rose Tico', 'BB-8'], set_series='Star Wars').save()

    Lego(name='', set_number=, piece_count=, source='', release_year=2017,
        image_url='', minifigures=['', '', ''], set_series='Star Wars').save()

    # Lego(name='', set_number=, piece_count=, source='', release_year=2017,
    #     image_url='', minifigures=['', '', ''], set_series='Star Wars').save()


def fallow(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')
    Lego.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('legos', '0017_auto_20210216_1813'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
