# Generated by Django 3.1.4 on 2021-02-17 19:24

from django.db import migrations


def seed(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')

    Lego(name='U-Wing Fighter', set_number=30496, piece_count=55, source='Rogue One', release_year=2017,
         image_url='https://images.brickset.com/sets/images/30496-1.jpg?201701030431', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='First Order Heavy Assault Walker', set_number=30497, piece_count=54, source='Episode VIII', release_year=2017,
         image_url='https://images.brickset.com/sets/images/30497-1.jpg?201709260948', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='R2-D2', set_number=30611, piece_count=70, source='Episode IV', release_year=2017,
         image_url='https://images.brickset.com/sets/images/30611-1.jpg?201703220726', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Scarif Stormtrooper', set_number=40176, piece_count=25, source='Rogue One', release_year=2017,
         image_url='https://images.brickset.com/sets/images/40176-1.jpg?201709041134', minifigures=['Scarif Stormtrooper'], set_series='Star Wars').save()
    Lego(name='R3-M2', set_number=40268, piece_count=21, source='Rogue One', release_year=2017,
         image_url='https://images.brickset.com/sets/images/40268-1.jpg?201703290940', minifigures=['R3-M2'], set_series='Star Wars').save()
    Lego(name='UCS Snowspeeder', set_number=75144, piece_count=1703, source='Episode V', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75144-1.jpg?201703220726', minifigures=['Zev Senesca', 'Will Scotian'], set_series='Star Wars').save()
    Lego(name='U-wing Microfighter', set_number=75160, piece_count=109, source='Rogue One', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75160-1.jpg?201612020919', minifigures=['Rebel U-Wing Pilot'], set_series='Star Wars').save()
    Lego(name='TIE Striker Microfighter', set_number=75161, piece_count=88, source='Rogue One', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75161-1.jpg?201612020919', minifigures=['TIE Striker Pilot'], set_series='Star Wars').save()
    Lego(name='Y-wing Microfighter', set_number=75162, piece_count=90, source='Rogue One', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75162-1.jpg?201612020919', minifigures=['Rebel Y-Wing Pilot'], set_series='Star Wars').save()
    Lego(name='Krennic\'s Imperial Shuttle Microfighter', set_number=75163, piece_count=78, source='Rogue One', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75163-1.jpg?201612020919', minifigures=['Imperial Shuttle Pilot'], set_series='Star Wars').save()
    Lego(name='Rebel Trooper Battle Pack', set_number=75164, piece_count=120, source='Rogue One', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75164-1.jpg?201612020919', minifigures=['Rebel Trooper (4x)'], set_series='Star Wars').save()
    Lego(name='Imperial Trooper Battle Pack', set_number=75165, piece_count=112, source='Rogue One', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75165-1.jpg?201612020919', minifigures=['Imperial Death Trooper (2x)', 'Stormtrooper (2x)'], set_series='Star Wars').save()
    Lego(name='First Order Transport Speeder Battle Pack', set_number=75166, piece_count=117, source='Episode VII', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75166-1.jpg?201707191128', minifigures=['First Order Flametrooper', 'First Order Officer', 'First Order Stormtrooper (2x)'], set_series='Star Wars').save()
    Lego(name='Bounty Hunter Speeder Bike Battle Pack', set_number=75167, piece_count=125, source='Expanded Universe', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75167-1.jpg?201705210933', minifigures=['4-LOM', 'Bossk', 'Dengar', 'IG-88'], set_series='Star Wars').save()
    Lego(name='Yoda\'s Jedi Starfighter', set_number=75168, piece_count=262, source='Clone Wars', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75168-1.jpg?201611300919', minifigures=['Yoda', 'R2-D2'], set_series='Star Wars').save()
    Lego(name='Duel on Naboo', set_number=75169, piece_count=208, source='Episode I', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75169-1.jpg?201611300919', minifigures=['Qui-Gon Jinn', 'Obi-Wan Kenobi', 'Darth Maul'], set_series='Star Wars').save()
    Lego(name='The Phantom', set_number=75170, piece_count=269, source='Rebels', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75170-1.jpg?201611300919', minifigures=['Chopper', 'Kanan Jarrus', 'Admiral Thrawn'], set_series='Star Wars').save()
    Lego(name='Battle on Scarif', set_number=75171, piece_count=419, source='Rogue One', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75171-1.jpg?201612020919', minifigures=['Cassian Andor', 'Jyn Erso', 'Scarif Stormtrooper (2x)'], set_series='Star Wars').save()
    Lego(name='Y-wing Starfighter', set_number=75172, piece_count=691, source='Rogue One', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75172-1.jpg?201612020919', minifigures=['Admiral Raddus', 'R3-S1', 'Moroff', 'Rebel Pilot', 'Stormtrooper'], set_series='Star Wars').save()
    Lego(name='Luke\'s Landspeeder', set_number=75173, piece_count=149, source='Episode IV', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75173-1.jpg?201611300919', minifigures=['C-3PO', 'Ben Kenobi', 'Luke Skywalker', 'Tusken Raider'], set_series='Star Wars').save()
    Lego(name='Desert Skiff Escape', set_number=75174, piece_count=277, source='Episode VI', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75174-1.jpg?201611300919', minifigures=['Boba Fett', 'Han Solo', 'Chewbacca', 'Skiff Guard'], set_series='Star Wars').save()
    Lego(name='A-wing Starfighter', set_number=75175, piece_count=358, source='Episode VI', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75175-1.jpg?201611300919', minifigures=['Lando Calrissian', 'Rebel Ground Crew', 'Rebel A-Wing Pilot'], set_series='Star Wars').save()
    Lego(name='Resistance Transport Pod', set_number=75176, piece_count=294, source='Episode VIII', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75176-1.jpg?201709041134', minifigures=['Finn', 'Rose Tico', 'BB-8'], set_series='Star Wars').save()

    Lego(name='First Order Heavy Scout Walker', set_number=75177, piece_count=554, source='Episode VIII', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75177-1.jpg?201709041134', minifigures=['First Order Crew Member', 'First Order Flametrooper', 'General Hux', 'Resistance Trooper'], set_series='Star Wars').save()
    Lego(name='Jakku Quadjumper', set_number=75178, piece_count=457, source='Episode VII', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75178-1.jpg?201705170344', minifigures=['BB-8', 'Rey', 'Finn', 'First Order Heavy Assault Trooper', 'Unkar\'s Brute'], set_series='Star Wars').save()
    Lego(name='Kylo Ren\'s TIE Fighter', set_number=75179, piece_count=630, source='Episode VIII', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75179-1.jpg?201709041134', minifigures=['Kylo Ren', 'BB-9E', 'First Order Stormtrooper', 'First Order TIE Pilot'], set_series='Star Wars').save()
    Lego(name='Rathtar Escape', set_number=75180, piece_count=836, source='Episode VII', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75180-1.jpg?201705170344', minifigures=['Bala-Tik', 'Chewbacca', 'Han Solo', 'Guavian Security Guard (2x)'], set_series='Star Wars').save()
    Lego(name='Republic Fighter Tank', set_number=75182, piece_count=305, source='Clone Wars', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75182-1.jpg?201705170344', minifigures=['Aayla Secura', 'Battle Droid (2x)', 'Clone Trooper Gunner'], set_series='Star Wars').save()
    Lego(name='Darth Vader Transformation', set_number=75183, piece_count=282, source='Episode III', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75183-1.jpg?201705170344', minifigures=['Anakin Skywalker (Burned)', 'Darth Vader', 'Emperor Palpatine', 'FX Series Medical Assistant Droid', 'Medical Droid', 'Prowler 1000 Exploration Droid'], set_series='Star Wars').save()
    Lego(name='Star Wars Advent Calendar', set_number=75184, piece_count=309, source='Expanded Universe', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75184-1.jpg?201708021046', minifigures=['BB-8 (Santa)', 'First Order Snowtrooper', 'First Order Stormtrooper', 'Imperial Ground Crew', 'Imperial Officer', 'Imperial Officer', 'Resistance Officer', 'Sabine Wren', 'Unkar\'s Thug'], set_series='Star Wars').save()
    Lego(name='Tracker I', set_number=75185, piece_count=557, source='Expanded Universe', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75185-1.jpg?201705170344', minifigures=['Rowan', 'Emperor Palpatine', 'Imperial Probe Droid', 'M-OC Hunter Droid'], set_series='Star Wars').save()
    Lego(name='The Arrowhead', set_number=75186, piece_count=775, source='Expanded Universe', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75186-1.jpg?201705170344', minifigures=['Kordi', 'Quarrie', 'R0-GR', 'Stormtrooper', 'Zander'], set_series='Star Wars').save()
    Lego(name='BB-8', set_number=75187, piece_count=1106, source='Episode VIII', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75187-1.jpg?201709041134', minifigures=['BB-8'], set_series='Star Wars').save()
    Lego(name='Resistance Bomber', set_number=75188, piece_count=778, source='Episode VIII', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75188-1.jpg?201709041134', minifigures=['Poe Dameron', 'Nix Jerd', 'Resistance Bomber Pilot', 'Resistance Gunner Paige', 'Vice Admiral Holdo'], set_series='Star Wars').save()
    Lego(name='First Order Heavy Assault Walker', set_number=75189, piece_count=1376, source='Episode VIII', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75189-1.jpg?201708310746', minifigures=['Captain Poe Dameron', 'First Order Stormtrooper', 'First Order Walker Driver', 'Resistance Trooper', 'Rey'], set_series='Star Wars').save()
    Lego(name='First Order Star Destroyer', set_number=75190, piece_count=1416, source='Episode VIII', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75190-1.jpg?201709041134', minifigures=['First Order Stormtrooper (2x)', 'BB-9E', 'First Order Medical Droid', 'First Order Officer', 'First Order Shuttle Pilot', 'Supreme Leader Snoke'], set_series='Star Wars').save()
    Lego(name='Jedi Starfighter with Hyperdrive', set_number=75191, piece_count=825, source='Episode II', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75191-1.jpg?201705170344', minifigures=['Obi-Wan Kenobi', 'Boba Fett', 'Jango Fett', 'R4-P17'], set_series='Star Wars').save()
    Lego(name='UCS Millennium Falcon', set_number=75192, piece_count=7541, source='Episode VII', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75192-1.jpg?201708310401', minifigures=['BB-8', 'C-3PO', 'Chewbacca', 'Han Solo', 'Finn', 'Han Solo (Old)', 'Rey', 'Princess Leia'], set_series='Star Wars').save()
    Lego(name='Scarif Stormtrooper', set_number=75523, piece_count=89, source='Rogue One', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75523-1.jpg?201611300919', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Chirrut Îmwe', set_number=75524, piece_count=87, source='Rogue One', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75524-1.jpg?201611300919', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Baze Malbus', set_number=75525, piece_count=148, source='Rogue One', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75525-1.jpg?201611300919', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Elite TIE Fighter Pilot', set_number=75526, piece_count=94, source='Episode VII', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75526-1.jpg?201709041134', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Rey', set_number=75528, piece_count=85, source='Episode VIII', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75528-1.jpg?201709041134', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Elite Praetorian Guard', set_number=75529, piece_count=92, source='Episode VIII', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75529-1.jpg?201709041134', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Chewbacca', set_number=75530, piece_count=179, source='Episode VII', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75530-1.jpg?201709041134', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Stormtrooper Commander', set_number=75531, piece_count=100, source='Episode IV', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75531-1.jpg?201705170344', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Scout Trooper & Speeder Bike', set_number=75532, piece_count=452, source='Episode VI', release_year=2017,
         image_url='https://images.brickset.com/sets/images/75532-1.jpg?201705170344', minifigures=['None'], set_series='Star Wars').save()

    # Lego(name='', set_number=, piece_count=, source='', release_year=2018,
    #     image_url='', minifigures=['', '', ''], set_series='Star Wars').save()


def fallow(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')
    Lego.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('legos', '0017_auto_20210216_1813'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
