# Generated by Django 3.1.4 on 2021-02-26 18:14

from django.db import migrations


def seed(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')

    Lego(name='Kylo Ren\'s Shuttle', set_number=30380, piece_count=33, source='Episode VIII', release_year=2018,
         image_url='https://images.brickset.com/sets/images/30380-1.jpg?201712280421', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Imperial TIE Fighter', set_number=30381, piece_count=42, source='Solo', release_year=2018,
         image_url='https://images.brickset.com/sets/images/30381-1.jpg?201803191000', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Imperial AT-Hauler', set_number=30498, piece_count=49, source='Solo', release_year=2018,
         image_url='https://images.brickset.com/sets/images/30498-1.jpg?201812101046', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='BB-8', set_number=40288, piece_count=48, source='Episode VII', release_year=2018,
         image_url='https://images.brickset.com/sets/images/40288-1.jpg?201804190741', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='DJ', set_number=40298, piece_count=22, source='Solo', release_year=2018,
         image_url='https://images.brickset.com/sets/images/40298-1.jpg?201806020247', minifigures=['DJ'], set_series='Star Wars').save()
    Lego(name='Kessel Mine Worker', set_number=40299, piece_count=22, source='Solo', release_year=2018,
         image_url='https://images.brickset.com/sets/images/40299-1.jpg?201811301044', minifigures=['Kessel Mine Worker'], set_series='Star Wars').save()
    Lego(name='Han Solo Mudtrooper', set_number=40300, piece_count=22, source='Solo', release_year=2018,
         image_url='https://images.brickset.com/sets/images/40300-1.jpg?201810030355', minifigures=['Han Solo (Mudtrooper)'], set_series='Star Wars').save()
    Lego(name='Y-wing Starfighter', set_number=75181, piece_count=1967, source='Episode VI', release_year=2018,
         image_url='https://images.brickset.com/sets/images/75181-1.jpg?201804030314', minifigures=['R@-BHD', 'Dutch Vander'], set_series='Star Wars').save()
    Lego(name='Millennium Falcon Microfighter', set_number=75193, piece_count=92, source='Episode IV', release_year=2018,
         image_url='https://images.brickset.com/sets/images/75193-1.jpg?201712150119', minifigures=['Chewbacca'], set_series='Star Wars').save()
    Lego(name='First Order TIE Fighter Microfighter', set_number=75194, piece_count=91, source='Episode VII', release_year=2018,
         image_url='https://images.brickset.com/sets/images/75194-1.jpg?201712150119', minifigures=['First Order TIE Pilot'], set_series='Star Wars').save()
    Lego(name='Ski Speeder vs. First Order Walker Microfighters', set_number=75195, piece_count=216, source='Episode VIII', release_year=2018,
         image_url='https://images.brickset.com/sets/images/75195-1.jpg?201712150926', minifigures=['First Order Walker Driver', 'Nodin Chavri'], set_series='Star Wars').save()
    Lego(name='A-Wing vs. TIE Silencer Microfighters', set_number=75196, piece_count=188, source='Episode VIII', release_year=2018,
         image_url='https://images.brickset.com/sets/images/75196-1.jpg?201712150119', minifigures=['Kylo Ren', 'Resistance A-Wing Pilot'], set_series='Star Wars').save()
    Lego(name='First Order Specialists Battle Pack', set_number=75197, piece_count=108, source='Episode VIII', release_year=2018,
         image_url='https://images.brickset.com/sets/images/75197-1.jpg?201712150119', minifigures=['First Order Stormtrooper Executioner (2x)', 'First Order Shuttle Pilot', 'First Order Crew Member'], set_series='Star Wars').save()
    Lego(name='Tatooine Battle Pack', set_number=75198, piece_count=97, source='Episode IV', release_year=2018,
         image_url='https://images.brickset.com/sets/images/75198-1.jpg?201712150119', minifigures=['Jawa (2x)', 'Tusken Raider', 'R3-T2'], set_series='Star Wars').save()
    Lego(name='General Grievous\' Combat Speeder', set_number=75199, piece_count=157, source='Episode III', release_year=2018,
         image_url='https://images.brickset.com/sets/images/75199-1.jpg?201712150926', minifigures=['Mace Windu', 'General Grievous'], set_series='Star Wars').save()
    Lego(name='Ahch-To Island Training', set_number=75200, piece_count=241, source='Episode VIII', release_year=2018,
         image_url='https://images.brickset.com/sets/images/75200-1.jpg?201712150926', minifigures=['Rey', 'Luke Skywalker'], set_series='Star Wars').save()
    Lego(name='First Order AT-ST', set_number=75201, piece_count=370, source='Episode VIII', release_year=2018,
         image_url='https://images.brickset.com/sets/images/75201-1.jpg?201801090126', minifigures=['Captain Phasma', 'BB-8', 'Finn (Disguise)', 'Rose Tico (Disguise)'], set_series='Star Wars').save()
    Lego(name='Defense of Crait', set_number=75202, piece_count=746, source='Episode VIII', release_year=2018,
         image_url='https://images.brickset.com/sets/images/75202-1.jpg?201712150119', minifigures=['Admiral Ematt', 'Poe Dameron', 'First Order Snowtrooper (2x)', 'Resistance Trooper'], set_series='Star Wars').save()
    Lego(name='Hoth Medical Chamber', set_number=75203, piece_count=255, source='Episode V', release_year=2018,
         image_url='https://images.brickset.com/sets/images/75203-1.jpg?201807240822', minifigures=['Luke Skywalker', 'Princess Leia', 'Medical Droid', 'Medical Assistant Droid'], set_series='Star Wars').save()
    Lego(name='Sandspeeder', set_number=75204, piece_count=278, source='Expanded Universe', release_year=2018,
         image_url='https://images.brickset.com/sets/images/75204-1.jpg?201711240145', minifigures=['Sandspeeder Gunner', 'Sandspeeder Pilot'], set_series='Star Wars').save()
    Lego(name='Mos Eisley Cantina', set_number=75205, piece_count=376, source='Episode IV', release_year=2018,
         image_url='https://images.brickset.com/sets/images/75205-1.jpg?201712150926', minifigures=['Greedo', 'Han Solo', 'Sandtrooper', 'Wuher'], set_series='Star Wars').save()
    Lego(name='Jedi and Clone Troopers Battle Pack', set_number=75206, piece_count=102, source='Episode II', release_year=2018,
         image_url='https://images.brickset.com/sets/images/75206-1.jpg?201804100929', minifigures=['Ki-Adi-Mundi', 'Barriss Offee', 'Clone Trooper (2x)'], set_series='Star Wars').save()

    # Lego(name='', set_number=, piece_count=, source='', release_year=2018,
    #     image_url='', minifigures=['', '', ''], set_series='Star Wars').save()

def fallow(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')
    Lego.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('legos', '0018_auto_20210217_1924'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
