# Generated by Django 3.1.4 on 2021-03-15 19:21

from django.db import migrations


def seed(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')

    Lego(name='Naboo Starfighter', set_number=30383, piece_count=48, source='Episode I', release_year=2019,
         image_url='https://images.brickset.com/sets/images/30383-1.jpg?201905310930', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Snowspeeder', set_number=30384, piece_count=49, source='Episode V', release_year=2019,
         image_url='https://images.brickset.com/sets/images/30384-1.jpg?201904041247', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Podracer', set_number=30461, piece_count=58, source='Episode I', release_year=2019,
         image_url='https://images.brickset.com/sets/images/30461-1.jpg?201904041247', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Obi-Wan Kenobi - Collectable Minifigure', set_number=30624, piece_count=12, source='Episode IV', release_year=2019,
         image_url='https://images.brickset.com/sets/images/30624-1.jpg?201912050753', minifigures=['Obi-Wan Kenobi'], set_series='Star Wars').save()
    Lego(name='Battle of Hoth - 20th Anniversary Edition', set_number=40333, piece_count=195, source='Episode V', release_year=2019,
         image_url='https://images.brickset.com/sets/images/40333-1.jpg?201904270648', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Battle of Endor', set_number=40362, piece_count=197, source='Episode VI', release_year=2019,
         image_url='https://images.brickset.com/sets/images/40362-1.jpg?201910031017', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Naboo Starfighter Microfighter', set_number=75223, piece_count=62, source='Episode I', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75223-1.jpg?201812140830', minifigures=['Anakin Skywalker'], set_series='Star Wars').save()
    Lego(name='Sith Infiltrator Microfighter', set_number=75224, piece_count=92, source='Episode I', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75224-1.jpg?201812140830', minifigures=['Darth Maul'], set_series='Star Wars').save()
    Lego(name='Elite Praetorian Guard Battle Pack', set_number=75225, piece_count=109, source='Episode VIII', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75225-1.jpg?201812140830', minifigures=['Elite Praetorian Guard (3x)', 'First Order Stormtrooper', 'Praetorian Training Droid'], set_series='Star Wars').save()
    Lego(name='Inferno Squad Battle Pack', set_number=75226, piece_count=118, source='Battlefront', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75226-1.jpg?201812140830', minifigures=['Iden Versio', 'Inferno Squad Agent (3x)'], set_series='Star Wars').save()
    Lego(name='Darth Vader Bust', set_number=75227, piece_count=327, source='Episode VI', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75227-1.jpg?201903210724', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Escape Pod vs. Dewback Microfighters', set_number=75228, piece_count=177, source='Episode VI', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75228-1.jpg?201812140830', minifigures=['C-3PO', 'R2-D2', 'Sandtrooper Captain'], set_series='Star Wars').save()
    Lego(name='Death Star Escape', set_number=75229, piece_count=329, source='Episode VI', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75229-1.jpg?201812140830', minifigures=['Luke Skywalker', 'Princess Leia', 'Mouse Droid', 'Stormtrooper'], set_series='Star Wars').save()
    Lego(name='Droid Gunship', set_number=75233, piece_count=389, source='Episode III', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75233-1.jpg?201812140830', minifigures=['Yoda', 'Chief Tarfful', 'Kashyyyk Battle Droid (2x)'], set_series='Star Wars').save()
    Lego(name='AT-AP Walker', set_number=75234, piece_count=689, source='Episode III', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75234-1.jpg?201812140830', minifigures=['Kashyyyk Battle Droid (2x)', 'Chewbacca', 'Clone Commander Gree', '41st Elite Corps Trooper'], set_series='Star Wars').save()
    Lego(name='X-wing Starfighter Trench Run', set_number=75235, piece_count=132, source='Episode IV', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75235-1.jpg?201812140830', minifigures=['Luke Skywalker', 'R2-D2', 'Stormtrooper'], set_series='Star Wars').save()
    Lego(name='Duel on Starkiller Base', set_number=75236, piece_count=191, source='Episode VII', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75236-1.jpg?201903210341', minifigures=['Rey', 'Kylo Ren'], set_series='Star Wars').save()
    Lego(name='TIE Fighter Attack', set_number=75237, piece_count=77, source='Episode IV', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75237-1.jpg?201812140830', minifigures=['TIE Fighter Pilot', 'Rebel Fleet Trooper'], set_series='Star Wars').save()
    Lego(name='Action Battle Endor Assault', set_number=75238, piece_count=193, source='Episode VI', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75238-1.jpg?201903210341', minifigures=['Scout Trooper', 'Wicket'], set_series='Star Wars').save()
    Lego(name='Hoth Generator Attack', set_number=75239, piece_count=235, source='Episode V', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75239-1.jpg?201903210341', minifigures=['Snowtrooper', 'Hoth Rebel Trooper'], set_series='Star Wars').save()
    Lego(name='Major Vonreg\'s TIE Fighter', set_number=75240, piece_count=496, source='Resistance', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75240-1.jpg?201903210341', minifigures=['R1-J5 (Bucket)', 'General Leia', 'Kaz Xiono', 'Major Vonreg'], set_series='Star Wars').save()
    Lego(name='Action Battle Echo Base Defence', set_number=75241, piece_count=504, source='Episode V', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75241-1.jpg?201903210341', minifigures=['Hoth Rebel Trooper (3x)', 'Imperial Probe Droid', 'Snowtrooper (2x)'], set_series='Star Wars').save()
    Lego(name='Black Ace TIE Interceptor', set_number=75242, piece_count=396, source='Resistance', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75242-1.jpg?201903210341', minifigures=['Griff Halloran', 'BB-8', 'Poe Dameron'], set_series='Star Wars').save()
    Lego(name='Slave I - 20th Anniversary Edition', set_number=75243, piece_count=1007, source='Episode V', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75243-1.jpg?201903210341', minifigures=['4-LOM', 'Boba Fett', 'Han Solo', 'Han Solo in Carbonite', 'Princess Leia', 'Zuckuss'], set_series='Star Wars').save()

    Lego(name='Tantive IV', set_number=75244, piece_count=1768, source='Episode IV', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75244-1.jpg?201904120858', minifigures=['R2-D2', 'Princess Leia', 'Bail Organa', 'C-3PO', 'Captain Antilles', 'Rebel Fleet Trooper'], set_series='Star Wars').save()
    Lego(name='Star Wars Advent Calendar', set_number=75245, piece_count=280, source='Expanded Universe', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75245-1.jpg?202004191234', minifigures=['Rebel Fleet Trooper', 'Battle Droid', 'Chewbacca', 'Cloud Car Pilot', 'Festive Gonk Droid', 'First Order Stormtrooper', 'Imperial Gunner', 'Luke Skywalker', 'Mouse Droid'], set_series='Star Wars').save()
    Lego(name='Death Star Cannon', set_number=75246, piece_count=159, source='Episode IV', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75246-1.jpg?201910040825', minifigures=['Obi-Wan Kenobi', 'Imperial Gunner'], set_series='Star Wars').save()
    Lego(name='Rebel A-wing Starfighter', set_number=75247, piece_count=62, source='Episode VI', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75247-1.jpg?201812140830', minifigures=['C-3PO', 'Rebel A-Wing Pilot'], set_series='Star Wars').save()
    Lego(name='Resistance A-wing Starfighter', set_number=75248, piece_count=269, source='Episode IX', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75248-1.jpg?201910040825', minifigures=['Lieutenant Connix', 'Snap Wexley'], set_series='Star Wars').save()
    Lego(name='Resistance Y-wing Starfighter', set_number=75249, piece_count=578, source='Episode IX', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75249-1.jpg?201910040825', minifigures=['Astromech Droid', 'D-O', 'First Order Snowtrooper', 'Poe Dameron', 'Zorii Bliss'], set_series='Star Wars').save()
    Lego(name='Pasaana Speeder Chase', set_number=75250, piece_count=373, source='Episode IX', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75250-1.jpg?201910040825', minifigures=['Rey', 'BB-8', 'First Order Jet Trooper', 'First Order Treadspeeder Driver'], set_series='Star Wars').save()
    Lego(name='Darth Vader\'s Castle', set_number=75251, piece_count=1060, source='Expanded Universe', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75251-1.jpg?201810030922', minifigures=['Darth Vader (Bacta Tank)', 'Darth Vader', 'Imperial Transport Pilot', 'Mouse Droid', 'Royal Guard (2x)'], set_series='Star Wars').save()
    Lego(name='Imperial Star Destroyer', set_number=75252, piece_count=4784, source='Episode IV', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75252-1.jpg?201909050158', minifigures=['Imperial Crew Member', 'Imperial Officer'], set_series='Star Wars').save()
    Lego(name='Droid Commander', set_number=75253, piece_count=1177, source='Expanded Universe', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75253-1.jpg?201905300148', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='AT-ST Raider', set_number=75254, piece_count=540, source='The Mandalorian', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75254-1.jpg?201910040825', minifigures=['Cara Dune', 'Klatooinian Raider (2x)', 'Din Djarin'], set_series='Star Wars').save()
    Lego(name='Yoda', set_number=75255, piece_count=1771, source='Episode III', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75255-1.jpg?201910040825', minifigures=['Yoda'], set_series='Star Wars').save()
    Lego(name='Kylo Ren\'s Shuttle', set_number=75256, piece_count=1005, source='Episode IX', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75256-1.jpg?201910040825', minifigures=['Kylo Ren', 'First Order Stormtrooper', 'General Pryde', 'Knight of Ren (2x)', 'Sith Trooper'], set_series='Star Wars').save()
    Lego(name='Millennium Falcon', set_number=75257, piece_count=1351, source='Episode IX', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75257-1.jpg?201910040825', minifigures=['R2-D2', 'Boolio', 'C-3PO', 'Chewbacca', 'D-O', 'Finn', 'Lando Calrissian'], set_series='Star Wars').save()
    Lego(name='Anakin\'s Podracer – 20th Anniversary Edition', set_number=75258, piece_count=279, source='Episode I', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75258-1.jpg?201903210341', minifigures=['Anakin Skywalker', 'Padme Amidala', 'Luke Skywalker'], set_series='Star Wars').save()
    Lego(name='Snowspeeder – 20th Anniversary Edition', set_number=75259, piece_count=309, source='Episode V', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75259-1.jpg?201903210341', minifigures=['Dak Ralter', 'Hoth Rebel Trooper', 'Luke Skywalker', 'Lando Calrissian'], set_series='Star Wars').save()
    Lego(name='Clone Scout Walker – 20th Anniversary Edition', set_number=75261, piece_count=250, source='Episode III', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75261-1.jpg?201903210341', minifigures=['Darth Vader', 'Battle Droid', 'Dward Spider Droid', '41st Elite Corps Trooper', 'Wookiee Warrior'], set_series='Star Wars').save()
    Lego(name='Imperial Dropship – 20th Anniversary Edition', set_number=75262, piece_count=125, source='Expanded Universe', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75262-1.jpg?201903210341', minifigures=['Han Solo', 'Stormtrooper (3x)', 'Shadow Trooper'], set_series='Star Wars').save()
    Lego(name='Mini Boost Droid Commander', set_number=75522, piece_count=62, source='Expanded Universe', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75522-1.jpg?201909080958', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Sith Trooper Bust', set_number=77901, piece_count=484, source='Episode IX', release_year=2019,
         image_url='https://images.brickset.com/sets/images/77901-1.jpg?201907101010', minifigures=['None'], set_series='Star Wars').save()


def fallow(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')
    Lego.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('legos', '0019_auto_20210226_1814'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
