# Generated by Django 3.1.4 on 2021-03-15 19:21

from django.db import migrations


def seed(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')

    Lego(name='Naboo Starfighter', set_number=30383, piece_count=48, source='Episode I', release_year=2019,
         image_url='https://images.brickset.com/sets/images/30383-1.jpg?201905310930', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Snowspeeder', set_number=30384, piece_count=49, source='Episode V', release_year=2019,
         image_url='https://images.brickset.com/sets/images/30384-1.jpg?201904041247', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Podracer', set_number=30461, piece_count=58, source='Episode I', release_year=2019,
         image_url='https://images.brickset.com/sets/images/30461-1.jpg?201904041247', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Obi-Wan Kenobi - Collectable Minifigure', set_number=30624, piece_count=12, source='Episode IV', release_year=2019,
         image_url='https://images.brickset.com/sets/images/30624-1.jpg?201912050753', minifigures=['Obi-Wan Kenobi'], set_series='Star Wars').save()
    Lego(name='Battle of Hoth - 20th Anniversary Edition', set_number=40333, piece_count=195, source='Episode V', release_year=2019,
         image_url='https://images.brickset.com/sets/images/40333-1.jpg?201904270648', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Battle of Endor', set_number=40362, piece_count=197, source='Episode VI', release_year=2019,
         image_url='https://images.brickset.com/sets/images/40362-1.jpg?201910031017', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Naboo Starfighter Microfighter', set_number=75223, piece_count=62, source='Episode I', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75223-1.jpg?201812140830', minifigures=['Anakin Skywalker'], set_series='Star Wars').save()
    Lego(name='Sith Infiltrator Microfighter', set_number=75224, piece_count=92, source='Episode I', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75224-1.jpg?201812140830', minifigures=['Darth Maul'], set_series='Star Wars').save()
    Lego(name='Elite Praetorian Guard Battle Pack', set_number=75225, piece_count=109, source='Episode VIII', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75225-1.jpg?201812140830', minifigures=['Elite Praetorian Guard (3x)', 'First Order Stormtrooper', 'Praetorian Training Droid'], set_series='Star Wars').save()
    Lego(name='Inferno Squad Battle Pack', set_number=75226, piece_count=118, source='Battlefront', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75226-1.jpg?201812140830', minifigures=['Iden Versio', 'Inferno Squad Agent (3x)'], set_series='Star Wars').save()
    Lego(name='Darth Vader Bust', set_number=75227, piece_count=327, source='Episode VI', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75227-1.jpg?201903210724', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='Escape Pod vs. Dewback Microfighters', set_number=75228, piece_count=177, source='Episode VI', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75228-1.jpg?201812140830', minifigures=['C-3PO', 'R2-D2', 'Sandtrooper Captain'], set_series='Star Wars').save()
    Lego(name='Death Star Escape', set_number=75229, piece_count=329, source='Episode VI', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75229-1.jpg?201812140830', minifigures=['Luke Skywalker', 'Princess Leia', 'Mouse Droid', 'Stormtrooper'], set_series='Star Wars').save()
    Lego(name='Droid Gunship', set_number=75233, piece_count=389, source='Episode III', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75233-1.jpg?201812140830', minifigures=['Yoda', 'Chief Tarfful', 'Kashyyyk Battle Droid (2x)'], set_series='Star Wars').save()
    Lego(name='AT-AP Walker', set_number=75234, piece_count=689, source='Episode III', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75234-1.jpg?201812140830', minifigures=['Kashyyyk Battle Droid (2x)', 'Chewbacca', 'Clone Commander Gree', '41st Elite Corps Trooper'], set_series='Star Wars').save()
    Lego(name='X-wing Starfighter Trench Run', set_number=75235, piece_count=132, source='Episode IV', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75235-1.jpg?201812140830', minifigures=['Luke Skywalker', 'R2-D2', 'Stormtrooper'], set_series='Star Wars').save()
    Lego(name='Duel on Starkiller Base', set_number=75236, piece_count=191, source='Episode VII', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75236-1.jpg?201903210341', minifigures=['Rey', 'Kylo Ren'], set_series='Star Wars').save()
    Lego(name='TIE Fighter Attack', set_number=75237, piece_count=77, source='Episode IV', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75237-1.jpg?201812140830', minifigures=['TIE Fighter Pilot', 'Rebel Fleet Trooper'], set_series='Star Wars').save()
    Lego(name='Action Battle Endor Assault', set_number=75238, piece_count=193, source='Episode VI', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75238-1.jpg?201903210341', minifigures=['Scout Trooper', 'Wicket'], set_series='Star Wars').save()
    Lego(name='Hoth Generator Attack', set_number=75239, piece_count=235, source='Episode V', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75239-1.jpg?201903210341', minifigures=['Snowtrooper', 'Hoth Rebel Trooper'], set_series='Star Wars').save()
    Lego(name='Major Vonreg\'s TIE Fighter', set_number=75240, piece_count=496, source='Resistance', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75240-1.jpg?201903210341', minifigures=['R1-J5 (Bucket)', 'General Leia', 'Kaz Xiono', 'Major Vonreg'], set_series='Star Wars').save()
    Lego(name='Action Battle Echo Base Defence', set_number=75241, piece_count=504, source='Episode V', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75241-1.jpg?201903210341', minifigures=['Hoth Rebel Trooper (3x)', 'Imperial Probe Droid', 'Snowtrooper (2x)'], set_series='Star Wars').save()
    Lego(name='Black Ace TIE Interceptor', set_number=75242, piece_count=396, source='Resistance', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75242-1.jpg?201903210341', minifigures=['Griff Halloran', 'BB-8', 'Poe Dameron'], set_series='Star Wars').save()
    Lego(name='Slave I - 20th Anniversary Edition', set_number=75243, piece_count=1007, source='Episode V', release_year=2019,
         image_url='https://images.brickset.com/sets/images/75243-1.jpg?201903210341', minifigures=['4-LOM', 'Boba Fett', 'Han Solo', 'Han Solo in Carbonite', 'Princess Leia', 'Zuckuss'], set_series='Star Wars').save()

    Lego(name='', set_number=, piece_count=, source='Episode IV', release_year=2019,
         image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='Expanded Universe', release_year=2019,
         image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='Episode IV', release_year=2019,
         image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='Episode VI', release_year=2019,
         image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='Episode IX', release_year=2019,
         image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='Episode IX', release_year=2019,
         image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='Episode IX', release_year=2019,
         image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='Expanded Universe', release_year=2019,
         image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='Episode IV', release_year=2019,
         image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='Expanded Universe', release_year=2019,
         image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='The Mandalorian', release_year=2019,
         image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='Episode III', release_year=2019,
         image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='Episode IX', release_year=2019,
         image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='Episode IX', release_year=2019,
         image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='Episode I', release_year=2019,
         image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='Episode V', release_year=2019,
         image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='Episode III', release_year=2019,
         image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='Expanded Universe', release_year=2019,
         image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='Expanded Universe', release_year=2019,
         image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=, piece_count=, source='Episode IX', release_year=2019,
         image_url='', minifigures=['', '', ''], set_series='Star Wars').save()


def fallow(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')
    Lego.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('legos', '0019_auto_20210226_1814'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
