# Generated by Django 3.1.4 on 2021-03-29 18:27

from django.db import migrations

def seed(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')

    Lego(name='', set_number=30386, piece_count=, source='Episode IX', release_year=2020,
        image_url='', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='', set_number=40407, piece_count=, source='Episode VI', release_year=2020,
        image_url='', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='', set_number=75263, piece_count=, source='Episode IX', release_year=2020,
        image_url='', minifigures=[''], set_series='Star Wars').save()
    Lego(name='', set_number=75264, piece_count=, source='Episode IX', release_year=2020,
        image_url='', minifigures=[''], set_series='Star Wars').save()
    Lego(name='', set_number=75265, piece_count=, source='Episode IV', release_year=2020,
        image_url='', minifigures=['', ''], set_series='Star Wars').save()
    Lego(name='', set_number=75266, piece_count=, source='Episode IX', release_year=2020,
        image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=75267, piece_count=, source='The Mandalorian', release_year=2020,
        image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=75268, piece_count=, source='Episode V', release_year=2020,
        image_url='', minifigures=['', ''], set_series='Star Wars').save()
    Lego(name='', set_number=75269, piece_count=, source='Episode III', release_year=2020,
        image_url='', minifigures=['', ''], set_series='Star Wars').save()
    Lego(name='', set_number=75270, piece_count=, source='Episode IV', release_year=2020,
        image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=75271, piece_count=, source='Episode IV', release_year=2020,
        image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=75272, piece_count=, source='Episode IX', release_year=2020,
        image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=75273, piece_count=, source='Episode IX', release_year=2020,
        image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=75274, piece_count=, source='Expanded Universe', release_year=2020,
        image_url='', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='', set_number=75275, piece_count=, source='Episode VI', release_year=2020,
        image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=75276, piece_count=, source='Expanded Universe', release_year=2020,
        image_url='', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='', set_number=75277, piece_count=, source='Expanded Universe', release_year=2020,
        image_url='', minifigures=['None'], set_series='Star Wars').save()
    Lego(name='', set_number=75278, piece_count=, source='Episode IX', release_year=2020,
        image_url='', minifigures=['D-O'], set_series='Star Wars').save()
    Lego(name='', set_number=75279, piece_count=, source='Expanded Universe', release_year=2020,
        image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=75280, piece_count=, source='Clone Wars', release_year=2020,
        image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=75281, piece_count=, source='Episode III', release_year=2020,
        image_url='', minifigures=['', ''], set_series='Star Wars').save()
    Lego(name='', set_number=75283, piece_count=, source='Clone Wars', release_year=2020,
        image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=75284, piece_count=, source='Episode IX', release_year=2020,
        image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=75286, piece_count=, source='Episode III', release_year=2020,
        image_url='', minifigures=['', '', ''], set_series='Star Wars').save()
    Lego(name='', set_number=75288, piece_count=, source='Episode V', release_year=2020,
        image_url='', minifigures=['', '', ''], set_series='Star Wars').save()

    # Lego(name='', set_number=, piece_count=, source='', release_year=2020,
    #     image_url='', minifigures=['', '', ''], set_series='Star Wars').save()

def fallow(apps, schema_editor):
    Lego = apps.get_model('legos', 'Lego')
    Lego.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('legos', '0020_auto_20210315_1921'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
